<?php
/*=======================================================================
 Nuke-Evolution Basic: Enhanced PHP-Nuke Web Portal System
 =======================================================================*/

/***************************************************************************
      This file was automatically generated by Admin FAQ Editor
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
 
// 
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// DO NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//

$faq[] = array("--", "<b>Reglas del Foro</b>");
$faq[] = array("Nota", "Por favor, lee y acepta las siguentes reglas e indicaciones.<br />");  //Please read and accept the following Rules and Guidelines
$faq[] = array("01. Bienvenido a nuestra p&aacute;gina Web", "Nuestra p&aacute;gina Web ofrece varias adiciones para ayudar hacer m&aacute;s enriquecedora y f&aacute;cil su experiencia en este Sitio Web y sus Foros. Por favor, t&oacute;mate un tiempo para familiarizarte con las caracter&iacute;sticas y reglas. &iexcl;Muchas gracias y que la pases bien!<br />");
$faq[] = array("02. B&uacute;squeda y los FAQ del Foro", "Antes de escribir un mensaje, por favor <a href=\"modules.php?name=Forums&file=search\"><u><b>Busca</b></u></a> en los <a href=\"modules.php?name=Forums&file=index\"><u><b>Foros</b></u></a> y da una mirada a la p&aacute;gina de los <a href=\"modules.php?name=Forums&file=faq\"><u><b>FAQ del Foro</b></u></a> si usted tiene problemas con los foros. Cuando haga una b&uacute;squeda, intente ser espec&iacute;fico en ella.<br />");
$faq[] = array("03. Evite los siguientes t&iacute;tulos para sus temas", "Cuando env&iacute;e mensajes, por favor evite darle un t&iacute;tulo a su tema tal como:<br />[list]<br />[*] &iexcl;AYUDA POR FAVOR! <br />[*] &iexcl;NECESITO AYUDA! <br />[*] Tengo una pregunta. <br />[*] &iexcl;GRAN problema! <br />[*] &iexcl;NOVATO necesita ayuda! <br />[*] Problemas <br />[*] &iexcl;URGENTE! <br />[*] &iexcl;AY&uacute;DAME POR FAVOR!<br />[*] NECESITO AYUDA R&aacute;PIDA.[/list]<br />o CUALQUIERA como las mencionadas! <br /><br />Por favor intenta ser tan espec&iacute;fico como sea posible en elegir un t&iacute;tulo para tu mensaje. Esto no s&oacute;lo nos ayudar&aacute; a tener una idea del contenido, tambi&eacute;n ayuda a encontrar un tema m&aacute;s r&aacute;pido lo que resultar&aacute; en respuestas m&aacute;s r&aacute;pidas.<br />");
$faq[] = array("04. Ay&uacute;danos, te ayudamos. Cuando crees un tema, proporciona toda la informaci&oacute;nm que te sea posible", "Cuando gustes enviar algo y preguntar por informaci&oacute;n o ayuda, por favor intenta darnos tanta informaci&oacute;n como sea posible en orden de hacernos m&aacute;s sencillo el darte una respuesta.<br />");
$faq[] = array("05. Si es posible usa temas similares existentes", "Por favor intenta empezar nuevos temas s&oacute;lo si es necesario. Si ya existe un tema similar, por favor escribe en &eacute;l. Esto mover&aacute; al tema a la pare superior de la lista y tu mensaje ser&aacute; apreciado. Tambi&eacute;n es una buena idea dado que habr&aacute;n algunos usuarios suscritos a notificaci&oacute;n de ese mensaje.<br />");
$faq[] = array("06. Env&iacute;a tu tema en el Foro Respectivo", "Por favor env&iacute;a tu tema en el Foro m&aacute;s apropiado. Esto no s&oacute;lo nos ayudar&aacute; a encontrar y responder tus problemas m&aacute;s r&aacute;pido, tambi&eacute;n ayuda a tener un foro organizado en nuestro Sitio Web y ayudar&aacute; a todos a encontrar lo que est&aacute;n buscando.");
$faq[] = array("07. Reportando Problemas / Bugs y otros comentarios", "Si usted viene a trav&eacute;s de un problema o bug mientras navega nuestro Sitio Web, por favor rep&oacute;rtalo en el Foro apropiado, intenta incluir el mensaje de error mostrado e intenta describir que hubiera causado el erro. Si&eacute;ntete libre de solicitar caracter&iacute;sticas futuras o s&oacute;lo cont&aacute;ctanos si gustas. Gracias.<br />");
$faq[] = array("08. Cuida tu lenguaje", "Palabras sucias, ofensivas, racistas o crudas as&iacute; como el blasfemar NO ES es bien recibido. &iexcl;EST&aacute;S ADVERTIDO!<br />");
$faq[] = array("09. Insultos, Ataques &amp; Comentarios Fuera del Tema", "No se permiten insultos, ataques personales o comentarios fuera del tema: La idea es hacer de este un ambiente agradable para todos.<br />");
$faq[] = array("10. Malentendidos", "Se permite la posibilidad de malentendidos y s&eacute; paciente si alguno pregunta por una explicaci&oacute;n que parece ser obvia.<br />");
$faq[] = array("11. Censura &amp; Violaci&oacute;n a estas reglas", "Debatir sobre todo, incluso cuando se haya calantado est&aacute; animado. Esto no es sobre censura. Sin embargo, mientras nosotros no podamos vigilar cada mensaje, eliminaremos los mensajes llamando la atenci&oacute;n y consideramos que han violado estas reglas.<br />");
$faq[] = array("12. Temas /Mensajes M&uacute;ltiple &amp; Duplicados", "No est&aacute; permitido enviar el mismo mensaje a m&uacute;ltiples categor&iacute;as y / o temas. Los mensajes m&uacute;ltiples &amp; duplicados ser&aacute;n eliminados. Adem&aacute;s, al enviar un tema 2 &oacute; m&aacute;s veces no conseguir&aacute;s una respuesta m&aacute;s r&aacute;pida... har&aacute; que no consigas respuesta.<br />");
$faq[] = array("13. Warez", "No se tolerar&aacute; material con derechos de autor o registrados (warez).<br />");
$faq[] = array("14. Publicidad", "No se permiten avisos comerciales en nuestro Sitio Web. Existen otro sitios para eso. Gracias.<br />");

$faq[] = array("--", "<b>Otras Reglas</b>");
$faq[] = array("Nota", "Por favor lee y acepta la siguiente Regla global y Gu&iacute;a sobre el contactar a los administradores / webmasters y abuso del Sistema de Mensajes Privados.<br />");
$faq[] = array("01. No hay soporte v&iacute;a e-mail, Sistema de Mensajer&iacute;a Instant&aacute;nea o Mensajes Privados", "Por favor &iexcl;NO contacte a los administradores, webmasters ni moderadores por e-mail, Sistema de Mensajer&iacute;a Instant&aacute;nea como MSN, ICQ, Yahoo etc. o Sistema de Mensajes Privados con preguntas [b]A MENOS QUE[/b] ellos te hayan dicho! Los mensajes privados no invitados y preguntas forumladas privadamente ser&aacute;n ignoradas! Usa nuestros Foros para entrar en contacto con ellos.<br />");
$faq[] = array("02. Spam por el Sistema de Mensajes Privados", "El env&iacute;o de publicidad a tarv&eacute;s del Sistema de Mensajes Privados, no est&aacute; permitido. Nosotros tambi&eacute;n monitoreamos los Mensajes Privados para ver si esta regla se cumple. Si encontramos a alguien enviando publicidad a nuestros miembros o si es reportado con nostoros, tu IP ser&aacute; bloqueada sin previo aviso y para siempre. [b]NO SE DAR&aacute; ADVERTENCIA[/b].<br />");

?>