<?php
/*=======================================================================
 Nuke-Evolution   :   Enhanced Web Portal System
 ========================================================================

 Nuke-Evo Base          :   #$#BASE
 Nuke-Evo Version       :   #$#VER
 Nuke-Evo Build         :   #$#BUILD
 Nuke-Evo Patch         :   #$#PATCH
 Nuke-Evo Filename      :   #$#FILENAME
 Nuke-Evo Date          :   #$#DATE
 Nuke-Evo Author        :   ReOrGaNiSaTiOn

 Copyright (c) 2010 by The Nuke-Evolution Development Team
 ========================================================================

 LICENSE INFORMATIONS COULD BE FOUND IN COPYRIGHTS.PHP WHICH MUST BE
 DISTRIBUTED WITHIN THIS MODULEPACKAGE OR WITHIN FILES WHICH ARE
 USED FROM WITHIN THIS PACKAGE.
 IT IS 'NOT' ALLOWED TO DISTRIBUTE THIS MODULE WITHOUT THE ORIGINAL
 COPYRIGHT-FILE.
 ALL INFORMATIONS ABOVE THIS SECTION ARE 'NOT' ALLOWED TO BE REMOVED.
 THEY HAVE TO STAY AS THEY ARE.
 IT IS ALLOWED AND SHOULD BE DONE TO ADD ADDITIONAL INFORMATIONS IN
 THE SECTIONS BELOW IF YOU CHANGE OR MODIFY THIS FILE.

/*****[CHANGES]**********************************************************
-=[Base]=-
-=[Mod]=-
 ************************************************************************/

// General entries were no UTF-8 is accepted
$lang_install['Next']  = 'PROCHAINE ETAPE';
$lang_install['Back']  = 'DERNIERE ETAPE';
$lang_install['Restart']  = 'REDEMARRER';
$lang_install['Help']  = 'AIDE';
$lang_install['IMG_OK']  = 'Test ok';
$lang_install['IMG_BAD']  = 'Test &eacute;chou&eacute;';
$lang_install['IMG_WARN']  = 'Ce n\'est pas une erreur seulement un avertissement';
$lang_install['IMG_DONE']  = 'Done';

// General entries with UTF-8 support
$lang_install['Langcode'] = 'fr-fr';
$lang_install['Landdir']  = 'ltr';
$lang_install['No']  = 'Non';
$lang_install['Yes']  = 'Oui';

$lang_install['Head_Title'] = 'Installation';
$lang_install['Block_Title'] = 'Status';
$lang_install['Block_Step_0'] = 'Bienvenue';
$lang_install['Block_Step_1'] = 'Infos';
$lang_install['Block_Step_2'] = 'Configuration des Fichiers';
$lang_install['Block_Step_3'] = 'Configuration de la base de donn&eacute;es';
$lang_install['Block_Step_4'] = 'Installation de la base de donn&eacute;es';
$lang_install['Block_Step_5'] = 'Param&egrave;tres de base';
$lang_install['Block_Step_6'] = 'Compte administrateur';
$lang_install['Block_Step_7'] = 'Param&egrave;tres de base de la base de donn&eacutees';
$lang_install['Block_Step_8'] = 'Termin&eacute;';
$lang_install['Block_Step_9'] = 'Log';

// Help-System
if (!defined('_EVO_HELPSYSTEM')) {
    define('_EVO_HELPSYSTEM', 'Evo Help');
}

// Step Welcome
$lang_install['Welcome'] = 'F&eacute;licitation<br/><br/>Vous allez accomplir l\'installation >> '.$var_install['version'].' <<<br/>La proc&eacute;dure d\'installation va vous guider en vous donnant des informations dont vous avez besoin pour l\'installation, va faire des tests et configuer les param&egrave;tres de base pour vous';
$lang_install['Language_Select'] = 'Si vous n\'avez pas le choix pour d\'autres langues dans la bo&icirc;te de s&eacute;lection, alors vous ne copierez pas votre langue dans le dossier des fichiers de langues t&eacute;l&eacute;charg&eacute;s sur votre serveur.';
$lang_install['License_Header'] = 'S\'il vous pla&icirc;t, lisez attentivement ce Contrat de licence et soumettez votre agr&eacute;ment &agrave; celle-ci';
$lang_install['License_Agreement'] = 'Pour continuer avec cette installation, accepter ce contrat de licence.';
$lang_install['License_Text'] = '
                      I M P O R T A N T    N O T E
           --------------------------------------------------
   PLEASE READ AND ACCEPT THE FOLLOWING USER AGREEMENT IF YOU ARE USING
   THIS SOFTWARE PACKAGE OR ANY OF ITS CONTENT. THANKS:

   01. All copyright, credit and display notices used within this
       package must remain intact.

   02. All copyright, credit and display notices generated by this
       package must remain intact.

   03. All copyright, credit and display notices must remain visible
       and must remain intact in all locations.

   04. Modification and alteration of this package is done at the users
       own risk. This must only be done in compliance with all visual,
       internal display, modification and distribution terms.

   05. To ensure authenticity when downloading any material related to
       Nuke-Evolution Basic, download all / any material from the
       official mirror sites stated below. Material downloaded from
       non-official sources may contain malicious content and is not
       supported in any way by Nuke-Evolution Basic, the
       Nuke-Evolution Team or any of the authors of Nuke-Evolution
       material including authors of included scripts and authors of
       the CMS engine:

       - http://www.nuke-evolution.com

   06. All mods, blocks, modules, themes, code that was not explicitly
       created by the Nuke-Evolution team has been credited to the
       original author.

   07. Official support for every aspect of the project will only be
       provided by the Nuke-Evolution website.

       - http://www.evo-german.com

   08. For further license information please read the gpl text file
       include in "licenses and credits\Licenses\GPL"
  ======================================================================*/


 WARRANTY:
 ---------

 Because Nuke-Evolution Basic is licensed free of charge, there is no
 warranty for the package, to the extent permitted by applicable law.
 Except when otherwise stated in writing, the Nuke-Evolution Team
 provides Nuke-Evolution "as is" without warranty of any kind, either
 expressed or implied, including, but not limited to, the implied
 warranties of merchantability and fitness for a particular purpose.
 The entire risk as to the quality and performance of the package is
 with you. Should the package prove defective, you assume the cost of
 all necessary servicing, repair or correction.';





// Step Infos
$lang_install['Infos_Title'] = 'Nous avons v&eacuterif&eacute votre syst&egrave;me.<br />En-dessous vous trouverez les informations que nous avons trouv&eacute;es et si elles sont bonnes ou pas.<br />';
$lang_install['DB_Setup'] = 'Dans cette &eacutetape, nous initialisons la connection avec la base de donn&eacute;es.<br />Toutes les informations n&eacute;cessaires devraient &ecirc;tre fournis par votre fournisseur ou vous devriez les avoir d&eacute;finis lorsque vous avez cr&eacute;&eacute; la base de donn&eacute;e<br />';

// Language entries for Installer
$lang_install['Date']    = 'Date';
$lang_install['Step']    = 'Etape';
$lang_install['Last_Step']    = 'Derni&egrave;te &eacute;tape';
$lang_install['Log_Message']    = 'Message';
$lang_install['Submit'] = 'Soumettre';

$lang_install['Installation_started'] = 'D&eacute;but de l\'Installation';
$lang_install['Server_Configuration_Details'] = 'D&eacute;tails de la configuration du serveur';
$lang_install['Server_Configuration_Summary'] = 'R&eacute;sum&eacute; de la configuration du serveur';
$lang_install['DB_Installation'] = 'Cr&eacute;ation de tableaux de base de donn&eacute;es';
$lang_install['Installation_Start_failed'] = 'Nous avons trouv&eacute; une erreur critique, qui peut faire que malheureusement Evo-Cms ne peut fonctionner seulement sans erreur sur votre serveur.<br />Cliquez sur Aide ou consultez notre Wiki, La vous trouverez chaque param&egrave;tre de base dont vous avez besoin pour que l\'installation se d&eacute;roule bien.<br />Trucs, astuces et h&eacute;b&eacute;rgeurs, o&ugrave; Evo-Cms fonctionne, sont dans notre forum.';
$lang_install['Errors_found'] = 'Nous avons trouv&eacute; des erreurs';
$lang_install['Warnings_found'] = 'Nous avons trouv&eacute; des avertissements';

$lang_install['File_Setup'] = 'Configuration du fichier';
$lang_install['File_error'] = 'Erreur : Le fichier n\'est pas disponible.';
$lang_install['File_warning'] = 'Attention: Le fichier n\'est pas valide.';
$lang_install['File_notchanged'] = 'Avertissement: Les permissions ne sont pas correctes ';
$lang_install['File_done'] = 'Ok : les permissions ont &eacute;t&eacute; chang&eacute;es avec succ&egrave;s';
$lang_install['File_mustexist'] = 'Fichier doit exister - mais n\'est pas pr&eacute;sent. C\'est une erreur. Merci de regarder l\'aide pour voir l\'emplacement du fichier/r&eacute;pertoire et v&eacute;rifiez si vous avez t&eacute;l&eacute;charg&eacute; le fichier/r&eacute;pertoire';
$lang_install['File_shouldexist'] = 'Fichier devrait exister - mais n\'est pas pr&eacute;sent. Ce n\'est pas une erreur car le fichier est facultatif. Merci de regarder l\'aide pour voir l\'emplacement du fichier/r&eacute;pertoire.';

$lang_install['File_htaccess'] = 'Fichier : .htacess';
$lang_install['File_Help_htaccess'] = 'Fichier: .htacess<br />Chemin: root<br />Ce fichier est une extension de votre fichier de configuration du serveur web avec des directives pour celui-ci. Dans des environnements restreints, ce fichier pourrait entra&icirc;ner une erreur du serveur web alors nous le fournissons comme cela evo.htaccess. Vous pouvez essayer de le renommer en .htaccess. Si vous rencontrez des probl&egrave;mes avec le serveur web, renomer les fichier &agrave; nouveau en to evo.htaccess et vous pourrez poursuivre l\'installation.';

$lang_install['File_Help_htaccess'] = 'Fichier: .htacess<br />Chemin: racine<br />Vous trouverez le fichier dans votre r&eacute;pertoire racine.<br />Par d&eacute;faut le nom est evo.htaccess<br />Si nous ne pouvons renomer ce fichier, vous pouvez le faire manuellement via votre ftp.<br />Renommer le fichier evo_htaccess en .htaccess';
$lang_install['File_staccess'] = 'Fichier : .staccess';
$lang_install['File_Help_staccess'] = '';
$lang_install['File_ultramode'] = 'Fichier: Ultramode';
$lang_install['File_Help_ultramode'] = '';
$lang_install['File_errorlog'] = 'Fichier pour les erreurs de logging: errorlog.txt';
$lang_install['File_Help_errorlog'] = 'Fichier: error.log<br />Chemin: includes/log/<br />Dans ce fichier, tous les avertissements ou des erreurs sont enregistr&eacute;es. Si ce fichier n\'a pas les permissions correctement attribu&eacute;es, l\'enregistrement des erreurs ne pourra se faire.';
$lang_install['File_adminlog'] = 'Fichier pour les messages de logging administration : adminlog.txt';
$lang_install['File_Help_adminlog'] = 'Fichier: admin.log<br />Chemin: includes/log/<br />Dans ce fichier, tous les avertissements ou des erreurs d\'administration sont enregistr&eacute;es. Si ce fichier n\'a pas les permissions correctement attribu&eacute;es, l\'enregistrement des erreurs ne pourra se faire.';

$lang_install['File_ForumsCacheDir'] = 'R&eacute;pertoire : Forum Cache';
$lang_install['File_Help_ForumsCacheDir'] = '';
$lang_install['File_FilesDir'] = 'R&eacute;pertoire : Forum Fichier Up/Download';
$lang_install['File_Help_FilesDir'] = '';
$lang_install['File_FilesThumbDir'] = 'R&eacute;pertoire : Forum Thumbnails';
$lang_install['File_Help_FilesThumbDir'] = '';
$lang_install['File_AvatarDir'] = 'R&eacute;pertoire : Avatars';
$lang_install['File_Help_AvatarDir'] = '';
$lang_install['File_LangBBCode'] = 'Fichier : Fichier de langage pour BBCode';
$lang_install['File_Help_LangBBCode'] = '';
$lang_install['File_LangFAQ'] = 'Fichier : Fichier de langage pour FAQ';
$lang_install['File_Help_LangFAQ'] = '';
$lang_install['File_LangFAQAttach'] = 'Fichier : Fichier de langage pour FAQ Attachements';
$lang_install['File_Help_LangFAQAttach'] = '';
$lang_install['File_LangRules'] = 'Fichier: Fichier de langage pour les r&egrave;gles du forum';
$lang_install['File_Help_LangRules'] = '';
$lang_install['File_ForumModules'] = 'R&eacute;pertoire : Modules du forum';
$lang_install['File_Help_ForumModules'] = '';
$lang_install['File_ForumModulesCache'] = 'R&eacute;pertoire : Modules du forum Cache';
$lang_install['File_Help_ForumModulesCache'] = '';
$lang_install['File_ForumModulesCacheExplain'] = 'R&eacute;pertoire : Module du forum Cache Explications';
$lang_install['File_Help_ForumModulesCacheExplain'] = '';
$lang_install['File_SupportersImagesSupporters'] = 'R&eacute;pertoire : Supporter Banner';
$lang_install['File_Help_SupportersImagesSupporters'] = '';
$lang_install['File_IncludesCache'] = 'R&eacute;pertoire : Cachedirectory';
$lang_install['File_Help_IncludesCache'] = '';
$lang_install['File_IncludesCacheFile'] = 'Fichier : Cache de fichiers';
$lang_install['File_Help_IncludesCacheFile'] = '';
$lang_install['File_HTMLPurifierDecorator'] = 'R&eacute;pertoire : HTML-Purifier Decorator';
$lang_install['File_Help_HTMLPurifierDecorator'] = '';
$lang_install['File_HTMLPurifierSerializer'] = 'R&eacute;pertoire : HTML-Purifier Serializer';
$lang_install['File_Help_HTMLPurifierSerializer'] = '';
$lang_install['File_HTMLPurifierSerializerHtml'] = 'R&eacute;pertoire : HTML-Purifier Serializer-HTML';
$lang_install['File_Help_HTMLPurifierSerializerHtml'] = '';
$lang_install['File_IconModDefIcons'] = 'Fichier: Icon-Mod Icones d&eacute;finis';
$lang_install['File_Help_IconModDefIcons'] = '';
$lang_install['File_Configdb'] = 'Fichier : Configuration de base de donn&eacute;es';
$lang_install['File_Help_Configdb'] = '';
$lang_install['Downloads_Files_Dir'] = 'R&eacute;pertoire : T&eacute;l&eacute;chargement de fichiers';
$lang_install['Downloads_Files_Dir_Help'] = '';
$lang_install['File_CantOpen'] = 'Ne peut pas ouvrir le fichier';
$lang_install['File_CantWrite'] = 'Ne peut pas &eacute;crire le fichier';
$lang_install['File_CantChange'] = 'Les permissions du fichier ne peuvent &ecirc;tre chang&eacute;es';
$lang_install['File_ErrorChmod'] = 'Certains fichiers importants n\'ont pas les bonnes permissions<br />Nous avons essay&eacute; de les changer, mais nous ne sommes pas autoris&eacute;s &agrave; le faire.<br />Vous pouvez maintenant soit changer les permissions de fichiers vous-m&ecirc;me ou nous laissez faire avec FTP Connect.<br />Si vous voulez le faire vous-m&ecirc;me, vous trouverez dans l\' aide pour chaque fichier o&ugrave; il se trouve. Apr&egrave;s avoir fait cela, red&eacute;marrez l\'installation.<br />Pour ceux qui ne veulent pas le faire eux-m&ecirc;mes, vous pouvez cliquer sur les bouton de soumission ci-dessous. Il vous sera alors demand&eacute; un compte FTP valides. Apr&egrave;s cette &eacute;tape termin&eacute;e, red&eacute;marrez l\'installation.';
$lang_install['File_FTPChmod'] = 'D&eacute;but des modifiactions des permissions par FTP';
$lang_install['FTP_Configuration_Details'] = 'FTP Configuration';
$lang_install['FTP_User'] = 'FTP Utilisateur';
$lang_install['FTP_Pwd'] = 'FTP Mot de passe';
$lang_install['FTP_Host'] = 'FTP H&ocirc;te';
$lang_install['FTP_Path'] = 'FTP Chemin';
$lang_install['FTP_Port'] = 'FTP Port';
$lang_install['FTP_Help_User'] = 'Ici, vous devez ins&eacute;rer votre utilisateur FTP que vous avez utilis&eacute; pour t&eacute;l&eacute;charger les fichiers sur le serveur. Par défaut, nous montrons l\'utilisateur qui est propri&eacute;taire des fichiers sur votre serveur.';
$lang_install['FTP_Help_Pwd'] = 'Ici, vous devez mettre votre mot de passe utilisateur FTP.';
$lang_install['FTP_Help_Host'] = 'Le domain ou l\'adresse Ip de votre h&ocirc;te o&ugrave; nous pouvons nous connecter avec.<br />Ici, vous devez ins&eacute;rer les m&ecirc;mes valeurs que vous avez rentrer dans le logiciel FTP.';
$lang_install['FTP_Help_Port'] = 'Ici, vous devez ins&eacute;rer le port sur lequel le service FTP est en cours d\'ex&eacute;cution sur le serveur. Normalement, il s\'agit du Port: 21. Vous pouvez utiliser ici les m&ecirc;mes param&egrave;tres que vous avez utilis&eacute; dans le logiciel FTP. S\'il n\'y a pas d\'entr&eacute;e, vous pouvez laisser le port par d&eacute;faut.';
$lang_install['FTP_Help_Path'] = 'Le chemin o&ugrave; a &eacute;t&eacute; installer Evo sur votre serveur.<br />Merci d\'ajouter ici le chemin pour vous rendre au r&eacute;pertoire de votre site apr&egrave;s votre connexion par FTP. Cela signifie que vous devez ajouter le chemin du r&eacute;pertoire de votre installation si elle existe.<br />Si vous ne l\'avez pas install&eacute; dans un sous-r&eacute;pertoire, vous pouvez laisser ce champ vide.';
$lang_install['FTP_Error_Host'] = 'Nous ne pouvons pas nous connecter au serveur. Merci de v&earifiez si vous avez entr&eacute; les bonnes informations pour se connecter au FTP';
$lang_install['FTP_Error_Login'] = 'Soit nom d\'utilisateur Ftp ou le mot de passe sont erroné. Merci de v&eacute;rifier si vous avez entr&eacute; les m&ecirc;mes informations pour se connecter au FTP';

$lang_install['DB_Host'] = 'Nom d\'h&eacute;b&eacute;rgeur';
$lang_install['DB_Help_Host'] = 'Nom du serveur de la base de donn&eacute;es. Normalement \'localhost\', est celui que nous utilisons par d&eacute;faut. Vous pouvez utiliser l\'adresse IP aussi, ce qui r&eacute;duira Le DNS-lookups.'; 
$lang_install['DB_Name'] = 'Nom de la base de donn&eacute;e';
$lang_install['DB_Help_Name'] = 'Nom de la base de donn&eacute;es<br />Aussi, la base de donn&eacute;e a &eacute;t&eacute; cr&eacute;&eacute;e par le biais de votre fournisseur ( Dans ce cas vous devriez avoir le nom de votre fournisseur) ou vous avez cr&eacute;&eacute; la base de donn&eacute;es vous-m&ecirc;me  (dans ce cas nous avons besoin du nom que vous avez donn&eacute; &agrave; votre base de donn&eacute;es lors de sa cr&eacute;ation).';
$lang_install['DB_Username'] = 'Nom d\'utilisateur de connection';
$lang_install['DB_Help_Username'] = 'Nom d\'utilisateur de la base de donn&eacute;es<br />le nom d\'utilisateur sert &agrave; vous connecter &agrave; la base de donn&eacute;es.<br />Soit vous avez ce nom par ce fournisseur ou vous avez cr&eacute;&eacute; ce compte de la base de donn&eacute;e vous-m&ecirc;me.';
$lang_install['DB_Password'] = 'Mot de passe de la base de donn&eacute;es';
$lang_install['DB_Help_Password'] = 'Mot de passe de connection<br />Vous avez besoin du mot de passe pour vous connecter &agrave; la base de donn&eacute;es.<br />Soit vous avez re&ccedil;u votre mot de passe de votre fournisseur ou vous l\'avez cr&eacute;&eacute; vous-m&ecirc;me lors de la crvation de l\'utilisateur de la base de donn&eacute;e.';
$lang_install['DB_Type'] = 'Type de base de donn&eacute;e';
$lang_install['DB_Help_Type'] = 'Type de base de donn&eacute;e<br />Type de votre base de donn&eacute;. Nous avons v&eacute;rifi&eacute; votre syst&egrave;me.Tous les types de base de donn&eacute;es disponible pourraient &ecirc;tre choisis.';
$lang_install['DB_Prefix'] = 'Pr&eacute;fixe de table (Standard: evo_)';
$lang_install['DB_Help_Prefix'] = 'Pr&eacute;fixe de table<br />Chaque table doit avoir un nom unique dans la base de donn&eacute;e. Parce que vous pouvez utiliser votre base de donn&eacute;e pour plusieurs syst&egrave;mes, chaque syst&egrave;me doit utiliser son propore prefixe. Une cha&icirc;ne unique est ajout&eacute;e au nom de la table. Le standard pour votre systeme est \'evo_\'. Cela veut dire que chaque table que nous crVons ou utilisons commenceront par \'evo_\'.';
$lang_install['DB_Conf_wrong'] = 'Nous ne pouvons pas &eacute;tablir une connection du serveur de la base de donn&eacute;e.<br />S\'il vous pla&icirc;t v&eacute;rifiez vos entr&eacute;e et essayez encore';
$lang_install['DB_DB_wrong'] = 'Nous pouvons &eacute;tablir une connection au serveur de la base de donn&eacute;es, mais pas &agrave; votre base de donn&eacute;es.<br />S\'il vous pla&icirc;t v&eacute;rifiez vos entr&eacute;e et essayez encore';
$lang_install['DB_Conf_ok'] = 'Nous pouvons &eacute;tablir une connection &agrave; votre base de donn&eacutes;.<br />Vos entr&eacute;es &eacute;taient ok.';
$lang_install['DB_Prefix_exists'] = 'Il y a des tables existantes avec le m&ecirc;me prefixe.';
$lang_install['DB_Delete_Existing'] = 'Nous devons &eacute;craser/supprimer ces tables existantes';
$lang_install['DB_Help_Delete_Existing'] = 'Tables supprim&eacute;e/&eacute;cras&eacute;e<br /> nous avons trouv&eacute; les table dans votre base de donn&eacute;e soit d\'une vieille installationeither ou vous avez s&eacute;l&eacute;ctionn&eacute; un prefixe qui sont d&eacute;j&agrav; en fonction d\'un autre syst&egrave;me.<br />With \'No\', nous ne supprimons pas ces tables existantes. Nous v&eacute;rifions si tous les champs et les indices utilis&eacute;s sont disponibles. Si non, nous en ajoutons ou les changeons.<br />With \'Yes\' Nous supprimons les anciennes tables et en cr&eacute;ons de nouvelles. C\'est la m&eacute;thode la plus sure pour le bon fonctionnement du syst&egrave;me.';
$lang_install['DB_Help_Update_Existing'] = 'connection existante trouv&eacute;e<br/>Nous avons trouv&eacute; une fichier de configuration existante. Avec les informatiosn inclues, nous pouvons &eacute;tablir une connection &agrave; la base de donn&eacute;e.<br />Il semble, que cela peut &ecirc;tre une mise &agrave; jour plut&ocirc; qu\'une nouvlle installation.<br />Si vous s&eacute;l&eacute;ctionnez \'update\' nous v&eacute;rifions seulement les tables existantes et les changeons en uns nouvelle configuration ou ajoutons des tables qui n\'existent pas.';
$lang_install['DB_Update_Existing'] = 'Est-ce une mise &agrave; jour d\'une installation existante ou une nouvelle installation';
$lang_install['DB_Update_Question'] = 'Il semble qu\'il s\'agit d\'une mise &agrave; niveau, plut&ocirc;t que d\'une nouvelle installation. S\'il vous pla&icirc;t soumettre la mani&egrave;re dont l\'installateur doit g&eacute;rer cette installation.';
$lang_install['DB_Help_Update_Convert'] = 'Normalement, tous les anciens syst&egrave;mes n\'utilise pas le jeux de caract&egrave;res ISO-8859-1. Nuke-Evo> 2.1.0 utilise UTF-8, un jeux de caract&egrave;res international. Si vous s&eacute;lectionnez OUI, nous convertirons tous les champs de texte dans la base de donn&eacute;es en UTF-8.';
$lang_install['DB_Update_Convert'] = 'Le syt&egrave;me vous convertie le jeu de caract&egrave;res ISO-8859-1 &agrave; UTF-8 ?';
$lang_install['DB_Update'] = 'Mise &agrave; jour';
$lang_install['DB_No_Convertion'] = 'Pas de convertion';
$lang_install['DB_Convert'] = 'Convertion';
$lang_install['DB_Installation'] = 'Nouvelle installation';
$lang_install['DB_Table_Exists'] = 'Table existante';
$lang_install['DB_Table_NotExists'] = 'la table doit &ecirc;tre cr&eacute;&eacute;e';
$lang_install['DB_Table_Done'] = 'la table a bien &eacute;t&eacute; cr&eacute;&eacute;e';
$lang_install['DB_Table_Warning_override'] = 'Vous avez choisi de red&eacute;finir les tables existantes. Tous les datas dans ces tables vont &ecirc;tre perdues !!<br />Vous pouvez revenir en arri&egrave;re ou recommencer l\'installation si c\'&eacute;tait la mauvaise d&eacute;cision.';
$lang_install['DB_Table_Create_in_process'] = 'Cr&eacute;ation de la table en cours .... ne pas interrompre !!';
$lang_install['DB_Table_Deleted'] = 'Table supprim&eacute;e';
$lang_install['DB_Table_Created'] = 'Table cr&eacute;&eacute;e';
$lang_install['DB_Table_Checked'] = 'Table v&eacute;rifi&eacute;e';
$lang_install['DB_Table_Identical'] = 'La Table est identique aux param&egrave;tres de la nouvelle installation de la table';
$lang_install['DB_Table_Changed'] = 'Table a chang&eacute; pour s\'adapter aux paam&egrave;tres de la nouvelle installation de la table';
$lang_install['DB_Table_Created_not'] = 'La table ne peut pas &ecirc;tre cr&eacute;&eacute;e.Erreur importante.';
$lang_install['DB_Table_Changed_not'] = 'La table ne peut pas &ecirc;tre chang&eacute;&eacute;. Erreur importante';
$lang_install['DB_Table_Created_ready'] = 'L\'installation des tables est termin&eacute;e<br />A notre connaissance, il n\'y a pas eu d\'erreur ici.<br />Avec la prochaine &eacute;tape vous pouvez configurer votre syst&egrave;me pour le travail.';
$lang_install['DB_Table_Created_ready_error'] = 'L\'installation de la table est finie<br />Il y a eu des erreurs.<br />Veuillez v&eacute;rifier le log afin de voir ce qui s\'est produit.';
$lang_install['DB_Entry_Update_missed'] = 'Nous avons eu une erreur d\'insertion dans la base de donn&eacute;es';

// Language entries for Checks
$lang_install['Found_language'] = 'Nous avons d&eacute;t&eacute;ct&eacute; que vous utilisez ce langage';
$lang_install['Found_language_change'] = 'Si vous voulez changer de langage (qui serait aussi la base de langage pour votre syst&egraveme), vous pouvez choisir entre les langages que nous avons trouv&eacute;';

$lang_install['SystemInfo'] = 'Informations syst&ecirc;me';
$lang_install['Sysname']    = 'Syst&ecirc;me d\'exploitation';
$lang_install['SysNodename']= 'Nom du serveur';
$lang_install['SysDomain']  = 'Domaine du serveur';
$lang_install['SysRelease'] = 'R&eacute;vision du syst&ecirc;me d\'exploitation';
$lang_install['SysVersion'] = 'Version du syst&ecirc;me d\'exploitation';
$lang_install['SysMachine'] = 'Architecture du processeur';
$lang_install['SystemUserInfo']     = 'Information utilisateur du syst&ecirc;me';
$lang_install['SysUser']            = 'Utilisateur du syst&ecirc;me';
$lang_install['SysUserProcessID']   = 'ID utilisateur du syst&ecirc;me';
$lang_install['SysUserProcessName'] = 'Nom utilisateur du syst&ecirc;me';
$lang_install['SysGroup']           = 'Information groupe du syst&ecirc;me';
$lang_install['SysGroupProcessID']  = 'ID du groupe du syst&ecirc;me ';
$lang_install['SysGroupProcessName']= 'Nom du groupe du syst&ecirc;me';
$lang_install['FreeDiskSpace']    = 'Espace sur le disque libre';
$lang_install['No_Free_Disk_Space'] = 'Nous n\'avons pas d\'information sur votre espace libre sur le disque. veuillez v&eacute;erifier s\'il y en a suffisamment (> 50 MB).';
$lang_install['Safe_Mod']    = 'Mode de sauvegarde';
$lang_install['PHP_Version']    = 'PHP_Version';
$lang_install['Register_Globals']    = 'Registre Globale';
$lang_install['Captcha_enabled'] = 'Captcha disponible';
$lang_install['Open_Basedir'] = 'Open basedir est activ&eacute; et n\'autorise pas l\'acc&egrave;s en &eacute;criture aux fichiers que vous avez transf&eacute;r&eacute; par FTP sur votre serveur. L\'utilisateur FTP et le groupe sont diff&egrave;rent de l\'utilisateur et du groupe qu\'ex&eacute;cute le serveur web.';
$lang_install['Session_Support'] = 'Session Support';
$lang_install['CURL_Libary'] = ' Biblioth&egrave;que Curl';
$lang_install['File_Upload'] = 'Fichier t&eacute;l&eacute;charg&eacute;';
$lang_install['Size_MB'] = 'MB';
$lang_install['Size_GB'] = 'GB';
$lang_install['File_Upload_Maxsize'] = 'Taille de fichier maximale t&eacute;l&eacute;charg&eacute;';
$lang_install['SMTP_enabled'] = 'SMTP permis';
$lang_install['SMTP_host'] = 'SMTP H&ocirc;te';
$lang_install['SMTP_sender'] = 'STMP envoyeur';
$lang_install['SMTP_command'] = 'STMP commande';
$lang_install['FTP_enabled'] = 'FTP permis';
$lang_install['Max_Post_Size'] = 'Taille maximum que vous pouvez poster';
$lang_install['Mod_Rewrite'] = 'Mod R&eacute;&eacute;criture (Important pour l\'onglet Google)';
$lang_install['Mod_Rewrite_no'] = 'Vous ne pouvez pas utiliser l\'onglet Google , parce que le "mod_rewrite" (mod r&eacute;&eacute;criture) ne fonctionne pas dans votre syst&egraveme';
$lang_install['Mod_Rewrite_no_check'] = 'Nous ne pouvons pas v&eacute;rifier si le mod_rewrite (mod r&eacute;&eacute;criture) fonctionne . Alors il peut &ecirc;tre possible que vous ne pouvez pas utiliser l\'onglet Google.';
$lang_install['GD_Libary'] = 'Biblioth&egrave;que GD';
$lang_install['GD_Libary_JPEG'] = ' Biblioth&egrave;que GD - Support JPEG  (Important pour Captcha)';
$lang_install['Memory_Limit'] = 'M&eacute;moire limite utilisable';
$lang_install['Memory_Limit_not'] = 'Vous n\'avez pas de limite pour votre m&eacute;moire param&egrave;tr&eacute;e. Cela veut dire, que le programme peut utiliser la totalit&eacute; de la m&eacute;moire de votre syst&egrave;me(limit&eacute;e &agrave; 128 MB). Le plus important pour votre syst&egrave;me est qu\'ils peuvent ralentir votre syst&egrave;me pour d\'autres utilisateurs.';

// Language entries Base Configuration
$lang_install['Base_Setup'] = 'Param&egrave;tres de base<br />Ici vous d&eacute;finissez les param&egrave;tres important de votre syst&egrave;me.<br />Tous les param&egrave;tre peuvent &ecirc;tre chang&eacute; dans votre syst&egrave;me d\'administration apr&egrave;s que votre site soit en place et qu\'il fonctionne';
$lang_install['Base_Sitename'] = 'Nom du site';
$lang_install['Base_Help_Sitename'] = 'Le nom de votre site web.<br />Max. 200 charct&egrave;res.<br />Sera affich&eacute; dans le titre de la fen&ecirc;tre du navigateur et &agrave; l\'int&eacute;rieur du forum. Il est aussi utilis&eacute; comme Meta-Tag dans l\'en-t&ecric;te de votre site(a.e. pour les moteurs de recherche)';
$lang_install['Base_Sitename_no_entry'] = 'Ce champ ne doit pas &ecric;tre vide';
$lang_install['Base_Sitedescription'] = 'Description du site (max. 200 caracrt&egrave;re)';
$lang_install['Base_Help_Sitedescription'] = 'Une courte decription de votre site. Elle sera montr&eacute;e aux utilisateurs aussi';
$lang_install['Base_Descriptione_no_entry'] = 'Ce champ ne doit pas &ecirc;tre vide';
$lang_install['Base_Url'] = 'URL de votre site web (sans http://)';
$lang_install['Base_Help_Url'] = 'Le domaine de votre site web. Exemple: www.mondomaine.com';
$lang_install['Base_Url_no_entry'] = 'Ce champ ne doit pas &ecirc;tre vide';
$lang_install['Base_Server_Port'] = 'Port du site web.';
$lang_install['Base_Help_Server_Port'] = 'Port du serveur web.<br />Nombre: 5-chiffres.<br />Le port de votre serveur o&ugrave; votre serveur web est &agrave; l\'&eacute;coute. Normalement: 80 ou derri&egrave;re un proxy: 8080.';
$lang_install['Base_Server_Port_wrong_entry'] = 'Le port du serveur doit &ecirc;tre plus grand ou &eacute;quivalent &agrave; 80 et plus petit que 65535';
$lang_install['Base_Server_Port_no_entry'] = 'Ce champ ne doit pas &ecrictre vide';
$lang_install['Base_Cookie_Domain'] = 'Cookie de domaine';
$lang_install['Base_Help_Cookie_Domain'] = 'Le Cookie de domaine Domain est normalement le m&ecirc;me domaine que votre site web.';
$lang_install['Base_Cookie_Name_wrong_chars'] = 'Vous avez utilis&eacute;s des caract&egrave;res interdits pour votre Cookie-Domain';
$lang_install['Base_Cookie_Name_no_entry'] = 'Ce champ ne doit pas &ecirc;tre vide';
$lang_install['Base_Cookie_Domain_no_entry'] = 'Ce champ ne doit pas &ecirctre vide';
$lang_install['Base_Cookie_Path'] = 'Chemin d\'acc&egrave;s de Cookie.';
$lang_install['Base_Help_Cookie_Path'] = 'Si vous avez votre Evo-Installation dans un sous-r&eacute;pertoire du domaine, vous devez inserer ici l\'URL derri&egrave;re le nom du domaine';
$lang_install['Base_Cookie_Path_no_entry'] = 'Ce champ ne doit pas &ecirc;tre vide';
$lang_install['Base_Cookie_Name'] = 'Nom du Cookie';
$lang_install['Base_Help_Cookie_Name'] = 'Un unique nom pour votre Cookie.<br />Dans votre domaine ce nom doit &ecirc;tre uniquepour un cookie.<br />Seuls les nombres et les lettres sont autoris&eacute;s.';
$lang_install['Base_Cookie_Name_no_entry'] = 'Ce champ ne doit pas &ecirc;tre vide';
$lang_install['Base_Board_Email'] = 'Email du webmaster';

$lang_install['Base_Help_Board_Email'] = 'Eamil du webmaster<br />Will be used for all System-Emails as Sender.<br />In some System the email-address must be the same as used within the php-ini entries for smtp.';

$lang_install['Base_Board_Email_no_entry'] = 'Ce champ ne doit pas &ecirc;tre vide';
$lang_install['Base_Board_Email_Sig'] = 'Email-Signature';
$lang_install['Base_Help_Board_Email_Sig'] = 'Email-Signature.<br />Max. 200 caract&egrave;res<br />utilis&eacute;s dans les emails ou les messages comme signature.';
$lang_install['Base_Board_Email_Sig_no_entry'] = 'Ce champ ne doit pas &ecirc;tre vide';
$lang_install['Base_Board_Default_Lang'] = 'Langage de base';
$lang_install['Base_Help_Board_Default_Lang'] = 'Le langage de base.<br />Le langage de base pour votre site web. vous pouvez choisir entre les langages qu nous avons trouv&eacute; sur votre Nuke-Evo Installation.<br />Ceci poura &ecirc;tre chang&eacute; plus tard par  l\'administrateur.';
$lang_install['Base_Board_Default_Lang_no_entry'] = 'Ce champ ne doit pas &ecirc;tre vide';
$lang_install['Base_Board_Startdate'] = 'Date de d&eacute;marrage du site web';
$lang_install['Base_Help_Board_Startdate'] = 'Date de d&eacute;marrage du site web.<br />Sera utilis&eacute; comme <strong>officielle date de d&eacute;marrage</strong> de votre site web. Normallement la date d\'installation. Si votre site fonctionnera plus lontemps ou s\'il sera restart&eacute; plus tard, vous pouvez changer la date ici.';
$lang_install['Base_Board_Startdate_no_entry'] = 'Ce champ ne doit pas &ecirc;tre vide';
$lang_install['Base_Board_Dateformat'] = 'Format standard de date';
$lang_install['Base_Help_Board_Dateformat'] = 'Format standard de date.<br />Le format de date d&eacute;fini ici est utilis&eacute; pour tous les param&egrave;tres du syst&egrave;me de base.';
$lang_install['Base_Board_Dateformat_no_entry'] = 'Ce champ ne doit pas &ecric;tre vide';
$lang_install['Base_Board_Timezone'] = 'Fuseau horaire de votre site';
$lang_install['Base_Help_Board_Timezone'] = 'Fuseau horaire de votre site.<br /> votre site web est disponible dans le monde entier - Mais vos utilisateurs vivent dans diff&eacute;rents fuseaux horaire<br />Toutes les entr&eacute;es doivent &ecirc;tre r&egrave;l&eacute; en concordance avec le fuseau horaire d&eacute;fini.<br />Voici le fuseau horaire pour votre serveur.<br />Normallement le fuseau horaire choisi doit &ecirc celui o&ugrave; fonctionne votre serveur et non o&ugrave; vous vivez.';
$lang_install['Base_Board_Timezone_no_entry'] = 'Ce champ ne doit pas &ecirc;tre vide';
$lang_install['Base_Conf_wrong'] = 'Nous avons trouv&eacute; des erreurs dans votre base de configuration.<br />Veuillez v&eacute;rifier vos entr&eacute;es.';
$lang_install['Base_Conf_ok'] = 'Nous n\'avons pas trouv&eacute; d\'erreur dans les r&eacute;glages de configuration de base.<br />Dans la prochaine &eacute;tape nous allons cr&eacute;er l\'administrateur de votre site.';
$lang_install['Base_From_Update'] = 'Vous &ecirc;tes dans Update-Modus.<br />Les informations ci-dessous sont rassembl&eacute;es &agrave; partir de votre syst&egrave;me existant.';

// Language entries for creating Admin Account
$lang_install['Admin_Setup'] = 'Cr&eacute;ation d\'un compte d\'administrateur';
$lang_install['Admin_Configuration_Details'] = 'Administrateur';
$lang_install['Admin_Name'] = 'Nom d\'utilisation de l\'Administrateur (sera utilis&eacute; dans tous les posts &eacute;crits par l\'administrateur)';
$lang_install['Admin_Help_Name'] = 'Le nom d\'utilisateur de l\'administrateur sera utilis&eacute; dans chaque place, normallement un nom d\'utilisateur est montrer lorsqu\'une personne &eacute;crit un post ou vote a.s.o.';
$lang_install['Admin_Name_no_entry'] = 'Ce champ ne doit pas &ecirc;tre vide';
$lang_install['Admin_Homepage'] = 'Site web de l\'administrateur';
$lang_install['Admin_Help_Homepage'] = 'Site web de l\'administrateur<br />Un administrateur n\'est pas autoris&eacute; &agrave; voter pour son propore site. Les v&eacute;rifications vont &ecirc;tre faites sur l\'entr&eacute;e dans ce champ';
$lang_install['Admin_Homepage_no_entry'] = 'Ce champ ne doit pas &ecirc;tre vide';
$lang_install['Admin_Password'] = 'Mot de passe';
$lang_install['Admin_Help_Password'] = 'Mot de passe<br />Le mot de passe ne doit pas &ecirc;tre plus petit que 6 caract&&egrave;res et pas plus long que 25 caract&egrave;res.';
$lang_install['Admin_Password2'] = 'R&eacute;p&eacute;tez le mot de passe';
$lang_install['Admin_Password_no_entry'] = 'Ce champ ne doit pas &ecirc;tre vide';
$lang_install['Admin_Password_not_match'] = 'Le mot de passe ne correspond pas';
$lang_install['Admin_Password_not_match_existing'] = 'Le mot de passe ne correspond pas &agrave; celui existant dans la base de donn&eacute;es';
$lang_install['Admin_Help_Password2'] = 'R&eacute;p&eacute;tez le mot de passe<br />Parce qu\'il n\'est pas &eacute;ident de changer le mot de passe pour l\'administrateur du site, vous devez r&eacute;ptez le mot de passe pour &ecirc;tre s&ucirc;r de ne pas faire de fautes d\'orthographe.';
$lang_install['Admin_Lang'] = 'Langue pour l\'Administrateur';
$lang_install['Admin_Help_Lang'] = 'Langue pour l\'Administrateur.<br />L\'entr&eacute;e dans ce champ sera utilis&eacute; comme la langue par d&eacute;fault pour cet administrateur';
$lang_install['Admin_Lang_no_entry'] = 'Ce champ ne doit pas &ecirc;tre vide';
$lang_install['Admin_Create_User'] = 'Voulez-vous cr&eacute;er un compte d\'utilisateur avec le m&ecirc;me nom?';
$lang_install['Admin_Help_Create_User'] = 'Cr&eacute;er un compte d\'utilisateur<br />Pour des raisons de s&eacute;curit&eacute; vous ne devriezez pas un cr&eacute;er un. Car pour votre syst&egrave;me de maintenance il est plus facile d\'avoir un utilisateur identique &agrave l\'administrateur';
$lang_install['Admin_Create_User_no_entry'] = 'Ce champ ne doit pas &ecirc;tre vide';
$lang_install['Admin_Conf_wrong'] = 'Nous avons trouv&eacute; des erreur dans vos param&egrave;tres d\'administrateur.<br />Veuillez v&eacute;rifier vos entr&eacute;es.';
$lang_install['Admin_Conf_ok'] = 'Nous n\'avons pas trouv&eacute; d\'erreur dans vos param&egrave;tres d\'administrateur.<br />Avec la prochaine &eacute;tape, nous remplirons votre base de donn&eacute;es avec les informations g&eacute;n&eacute;rales de base et les param&egrave;tres que vous nous avez donn&eacute; dans les &eacute;tapes pr&eacute;c&eacute;dentes.';

// Language entries for Database Step
$lang_install['Base_Information_Setup'] = 'Remplissage de la base de donn&eacute;es avec les param&egrave;tres de base';
$lang_install['Base_Information_Details'] = 'Tables dans votre base de donn&eacute;es';
$lang_install['Base_Informations_NoNeed'] = 'Pas d\'information &agrave; ajouter &agrave; la base de donn&eacute;es';
$lang_install['Base_Informations_ToDo'] = 'Informations pour l\'insertion, disponible';
$lang_install['Base_Informations_Done'] = 'Informations d&eacute;j&agrave; ins&eacute;r&eacute;es';
$lang_install['Base_Informations_ready'] = 'Les param&egrave;tres de base sont ins&eacute;r&eacute;s dans votre base de donn&eacute;es.<br />Comme nous l\'avons v&eacute;rifi&eacute; il n\'y a pas d\'erreur.<br />Vous avez fini l\'installation avec succ&egrave;s.';
$lang_install['Base_Informations_in_process'] = 'Insertion des param&egrave;tres de base ... Ne pas interrompre !!';
$lang_install['Base_Information_DB_Success'] = 'Param&egrave;tres de base brillament ins&eacute;r&eacute;s dans la base de donn&eacute;es';
$lang_install['Base_Informations_ready_error'] = 'Nous avons trouv&eacute; des erreurs durant l\'insertion dans la base de donn&eacute;es.<br />Veuillez v&eacute;rifier votre installation.<br />Vous avez termin&eacute; votre installation avec des erreurs.';

// Language entries for Last Step
$lang_install['Information_Setup_Ready'] = 'F&eacute;licitations !<br />Vous avez termin&eacute; votre configuration.';
$lang_install['Information_Setup_Ready_allok'] = 'Nous n\'avons pas rencontr&eacute; d\'erreurs durant la proc&eacute;dure d\'installation.<br/>Cela veut dire que votre site web est maintenant configur&eacute; et pr&ecirc;t &agrave; l\'utilisation.';
$lang_install['Information_Setup_Ready_nostep'] = 'Toutes les &eacute;tapes d\'installation n\'ont pas &eacute;t&eacute; faites.<br />Lors des &eacute;tapes faites, nous n\'vons pas trouv&eacute; d\erreurs.<br />Nous ne pouvons pas dire si votre site fonctionne. Vous devez le v&eacute;erifier et refaire l\'installation s\'il y a des erreurs.';
$lang_install['Information_Setup_Ready_error'] = 'Nous avons trouv&eacute; des erreurs importantes.<br />Nous pensons qu\il serait bien de v&eacute;rifier le log et red&eacute;marrer l\'installation.';
$lang_install['Information_Setup_Ready_noinfo'] = 'Nous n\'avons pas d\'informations &agrave; propos de la proc&eacute;dure d\'installation.<br />Cela veut dire que nous ne pouvons pas dire s\'il y a des erreurs et si toutes les tables ont &eacute;t&eacute; cr&eacute;&eacute;es.<br />Nous pensons que le mieux est de red&eacute;marrer la proc&eacute;dure d\'installation.';
$lang_install['Information_Setup_GoHome'] = 'Allez sur votre nouvelle page d\'accueil';
$lang_install['Information_Setup_GoAdmin'] = 'Allez dans l\'administration de votre nouveau site web';


// Language entries for Database fields

$lang_install['Page_Top']    = 'Haut de page';
$lang_install['Left_Block']  = 'Block gauche';
$lang_install['Page_Bottom'] = 'Bas de Page';
$lang_install['Group_Administrators'] = 'Administrateurs';
$lang_install['Group_Moderators'] = 'Mod&eacute;rateurs';

$lang_install['bbboard_message_1'] = 'Ce message est montr&eacute; sur toutes les pages et tous les utilisateurs et &eacute;tirer &agrave; 80% de la largeur disponible.';
$lang_install['bbboard_message_2'] = 'Ce message est montr&eacute; seulement sut l\'index de la page et est seulement visible pour les utilisateurs enregistr&eacute;s.';

$lang_install['bbcategories_cat_title'] = 'G&eacute;n&eacute;ral';

$lang_install['bbconfig_board_disable_msg'] = 'Le panneau d\'administration est actuellement d&eacute;sactiv&eacute;...';
$lang_install['bbconfig_default_dateformat'] = 'D M d, Y g:i a';
$lang_install['bbconfig_locked_view_open'] = 'Verrouill&eacute; : <strike>';
$lang_install['bbconfig_locked_view_close'] = '</strike>';
$lang_install['bbconfig_global_view_open'] = 'Annonce globale:';
$lang_install['bbconfig_global_view_close'] = '';
$lang_install['bbconfig_announce_view_open'] = 'Annonce :';
$lang_install['bbconfig_announce_view_close'] = '';
$lang_install['bbconfig_sticky_view_open'] = 'Coller :';
$lang_install['bbconfig_sticky_view_close'] = '';
$lang_install['bbconfig_moved_view_open'] = 'Bouger :';
$lang_install['bbconfig_moved_view_close'] = '';

$lang_install['bbextension_groups_Images'] = 'Images';
$lang_install['bbextension_groups_Archives'] = 'Archives';
$lang_install['bbextension_groups_Plain_Text'] = 'Text uni';
$lang_install['bbextension_groups_Documents'] = 'Documents';
$lang_install['bbextension_groups_Real_Media'] = 'R&eacute;el Media';
$lang_install['bbextension_groups_Streams'] = 'Stream';
$lang_install['bbextension_groups_Flash_Files'] = 'Fichiers flash';

$lang_install['bbforums_forum_name'] = 'Site';

$lang_install['bbgroups_group_name_Anonymous'] = 'Anonyme';
$lang_install['bbgroups_group_name_Moderators'] = 'Mod&eacute;rateurs';
$lang_install['bbgroups_group_description_Moderators'] = 'Mod&eacute;rateurs de ce forum';
$lang_install['bbgroups_group_name_Administrators'] = 'Administrateurs';
$lang_install['bbgroups_group_description_Administrators'] = 'Administrateurs de ce forum';
$lang_install['bbgroups_group_name_Users'] = 'Utilisateurs';
$lang_install['bbgroups_group_description_Users'] = 'Groupe d\'utilisateur par d&eacute;fault';

$lang_install['bbposts_text_post_subject'] = 'Bienvenue &agrave; Evo-Cms!';
$lang_install['bbposts_text_post_text'] = 'Merci pour avoir install&eacute; Evo-Cms.<br /><br />Le groupe Evo a mis toutes ces forces dans cette proc&eacute;dure pour qu\'elle mette en place la plus rapide, la plus fonctionnelle et la plus svcuris&eacute;e des v&eacute;rsions de PHP-Nuke. Nous vous encourageons &agrave; lire toute la documentation anexe afin que vous compreniez pleinement le pouvoir au sein de Evo.<br /><br />Dans les archives originales que vous avez t&eacute;l&eacute;charg&eacute; vous trouverez d\'importants fichiers contenant des informations d\'aide.<br /><br />Le premier est le fichier "Install"  dont nous esp&egrave;rons que vous en avez d&eacute;j&agrave; pris connaissance;. Ce fichier contient trois documents qui vous aide &agrave; installer et configurer votre nouveau site Evo. Si vous n\'y &ecirc;tes pas all&eacute; veuillez le faire maintenant!<br /><br />Le deuxi&egrave;me fichier est "Help". Dans ce fichier vous trouverez des documents d\'aide que notre &eacute;quipe a mis en place pour expliquer certaines caract&eacute;ristiques de Evo. Vous trouverez aussi des documents qui vous aiderons &agrave; r&eacute;soudre quelque erreurs que vous executez en raison des param&egrave;tres du navigateur ou la configuration des logiciels.<br /><br />Le troisi&egrave;me est le fichier "Theme Edits". Si vous voulez convertir un PHP-Nuke th&egrave;me pour travailler avec Evo vous devez suivre les conditions d\'instruction sans ce fichier.<br /><br /> nous esp&eacute;rons que Evo sera le meilleure logiciel Nuke software que vous ayez utilis&eacute;. Ayez du plaisir et arr&ecirc;tez vous sur www.nuke-evolution.com pour les supports, les mises &agrave; jour ou juste pour dire salut!<br /><br />[b:16f8943d60]- l\'Equipe de Evo-Cms[/b:16f8943d60]';

$lang_install['bbquota_limits_Low'] = 'Basse';
$lang_install['bbquota_limits_Medium'] = 'Moyen';
$lang_install['bbquota_limits_High'] = 'Haut';

$lang_install['bbranks_rank_title_Site_Owner'] = 'Site Administrateur';
$lang_install['bbranks_rank_title_Site_Admin'] = 'Site Admin';

$lang_install['bbsmilies_Very_Happy'] = 'Vraiment Heureux';
$lang_install['bbsmilies_Smile'] = 'Sourir';
$lang_install['bbsmilies_Sad'] = 'Sad';
$lang_install['bbsmilies_Surprised'] = 'Surpris';
$lang_install['bbsmilies_Shocked'] = 'Choqu&eacute;';
$lang_install['bbsmilies_Confused'] = 'Confus';
$lang_install['bbsmilies_Cool'] = 'Cool';
$lang_install['bbsmilies_Laughing'] = 'Laughing';
$lang_install['bbsmilies_Mad'] = 'Mad';
$lang_install['bbsmilies_Razz'] = 'Razz';
$lang_install['bbsmilies_Embarassed'] = 'Embarass&eacute;';
$lang_install['bbsmilies_Crying_or_Very_sad'] = 'Crying or Very sad';
$lang_install['bbsmilies_Evil_or_Very_Mad'] = 'Evil or Very Mad';
$lang_install['bbsmilies_Twisted_Evil'] = 'Twisted Evil';
$lang_install['bbsmilies_Rolling_Eyes'] = 'Rolling Eyes';
$lang_install['bbsmilies_Wink'] = 'Wink';
$lang_install['bbsmilies_Exclamation'] = 'Exclamation';
$lang_install['bbsmilies_Question'] = 'Question';
$lang_install['bbsmilies_Idea'] = 'Id&eacute;e';
$lang_install['bbsmilies_Arrow'] = 'Arrow';
$lang_install['bbsmilies_Neutral'] = 'Neutre';
$lang_install['bbsmilies_Mr_Green'] = 'Mr. Green';

$lang_install['bbstats_module_info_long_name_modul1'] = 'Vue d\'ensemble Section Statistiques';
$lang_install['bbstats_module_info_extra_info_modul1'] = 'Ce module va imprimer un lien dans le Bloc liens vers le site de Statistique.\nVous &ecirc;tes en mesure de d&eacute;finir le nombre de colonnes affich&eacute;es pour ce module dans le panneau d\'administration -> Edit module.';
$lang_install['bbstats_module_info_long_name_modul2'] = 'Top Posters';
$lang_install['bbstats_module_info_extra_info_modul2'] = 'Ce module affiche les meilleurs poster.\n Post anonymene sont pas compt&eacute;s';
$lang_install['bbstats_module_info_long_name_modul3'] = 'Administrative Statistics';
$lang_install['bbstats_module_info_extra_info_modul3'] = 'Ce module affiche quelques statistiques au sujet de votre forum.\nIl est &agrave; peu pr&egrave;s le m&ecirc;me que vous &ecirc;tes capable de voir au sein du panneau d\'administration. ';
$lang_install['bbstats_module_info_long_name_modul4'] = 'Sujet les plus regard&eacute;';
$lang_install['bbstats_module_info_extra_info_modul4'] = 'Ce module affiche les sujets les plus consult&eacute;s.';
$lang_install['bbstats_module_info_long_name_modul5'] = 'Meilleur poster du mois';
$lang_install['bbstats_module_info_extra_info_modul5'] = 'Ce module ne n&eacute;cessite pas l\'histoire du site Mod,\n il affichera les Top Poster sur une base mensuelle.';
$lang_install['bbstats_module_info_long_name_modul6'] = 'Nouveaux sujets par mois';
$lang_install['bbstats_module_info_extra_info_modul6'] = 'Ce module va afficher les sujets cr&eacute;&eacute;s &agrave; votre forum dans une statistique mensuelle.';
$lang_install['bbstats_module_info_long_name_modul7'] = 'Sujets les plus int&eacute;ressants';
$lang_install['bbstats_module_info_extra_info_modul7'] = 'Ce module affiche les sujets les plus int&eacute;ressants.';
$lang_install['bbstats_module_info_long_name_modul8'] = 'Top Mots';
$lang_install['bbstats_module_info_extra_info_modul8'] = 'Ce module affiche les mots les plus utilisés sur votre forum.';
$lang_install['bbstats_module_info_long_name_modul9'] = 'Sujets les moins int&eacute;ressants';
$lang_install['bbstats_module_info_extra_info_modul9'] = 'Ce module affiche les sujets les moins int&eacute;ressants.';
$lang_install['bbstats_module_info_long_name_modul10'] = 'Les plus actifs d&eacute;mareur de post';
$lang_install['bbstats_module_info_extra_info_modul10'] = 'Ce module affiche les plus actifs d&eacute;mareur de post du forum.\n Les posteurs anonyme ne sont pas comptabilis&eacute;s.';
$lang_install['bbstats_module_info_long_name_modul11'] = 'Top Smileys';
$lang_install['bbstats_module_info_extra_info_modul11'] = 'Ce module affiche le top des smileys les plus utilis&eacute; sur votre forum.\nCe module utilise une table index de smiley pour mettre en cache les donn&eacute;es et n\'\n exige pas une re-indexation de tous les postes.';
$lang_install['bbstats_module_info_long_name_modul12'] = 'Nouveau utilisateur par mois';
$lang_install['bbstats_module_info_extra_info_modul12'] = 'Ce module affiche les utilisateurs enregistr&eacute;s de votre forum dans une statistique mensuelle.';
$lang_install['bbstats_module_info_long_name_modul13'] = 'Nouveau post par mois';
$lang_install['bbstats_module_info_extra_info_modul13'] = 'Ce module affiche les postes cr&eacute;&eacute;s dans le forum avec une statistique mensuelle.';
$lang_install['bbstats_module_info_long_name_modul14'] = 'Top posteur de la semaine (Site Historique Mod)';
$lang_install['bbstats_module_info_extra_info_modul14'] = 'Ce module ne n&eacute;cessite pas le Mod historique du site, \nIl affichera le top posteur sur une base hebdomadaire.';
$lang_install['bbstats_module_info_long_name_modul15'] = 'Top Attachements T&eacute;l&eacute;charg&eacute;';
$lang_install['bbstats_module_info_extra_info_modul15'] = 'Ce module permet d\'afficher les fichiers les plus t&eacute;l&eacute;charg&eacute;s.\n Le Mod pi&egrave;ce jointe Version 2.3.x doivent &ecirc;tre install&eacute;s afin que ce module focntionne.\nVous &ecirc;tes en mesure d\'exclure les images de trop de la statistique.';
$lang_install['bbstats_module_info_long_name_modul16'] = 'Plus actif des sujets';
$lang_install['bbstats_module_info_extra_info_modul16'] = 'Ce module affiche les sujets les plus actifs de votre forum.';

$lang_install['bbthemes_name_tr_color1_name'] = 'La couleur l&eacute;g&egrave;re de ligne';
$lang_install['bbthemes_name_tr_color2_name'] = 'La couleur moyennee de ligne';
$lang_install['bbthemes_name_tr_color3_name'] = 'La couleur fonc&eacute;e de ligne';
$lang_install['bbthemes_name_tr_class1_name'] = '';
$lang_install['bbthemes_name_tr_class2_name'] = '';
$lang_install['bbthemes_name_tr_class3_name'] = '';
$lang_install['bbthemes_name_th_color1_name'] = 'Border round the whole page';
$lang_install['bbthemes_name_th_color2_name'] = 'Outer table border';
$lang_install['bbthemes_name_th_color3_name'] = 'Inner table border';
$lang_install['bbthemes_name_th_class1_name'] = 'Silver gradient picture';
$lang_install['bbthemes_name_th_class2_name'] = 'Blue gradient picture';
$lang_install['bbthemes_name_th_class3_name'] = 'Fade-out gradient on index';
$lang_install['bbthemes_name_td_color1_name'] = 'Background for quote boxes';
$lang_install['bbthemes_name_td_color2_name'] = 'All white areas';
$lang_install['bbthemes_name_td_color3_name'] = '';
$lang_install['bbthemes_name_td_class1_name'] = 'Background for topic posts';
$lang_install['bbthemes_name_td_class2_name'] = '2nd background for topic posts';
$lang_install['bbthemes_name_td_class3_name'] = '';
$lang_install['bbthemes_name_fontface1_name'] = 'Main fonts';
$lang_install['bbthemes_name_fontface2_name'] = 'Additional topic title font';
$lang_install['bbthemes_name_fontface3_name'] = 'Form fonts';
$lang_install['bbthemes_name_fontsize1_name'] = 'Smallest font size';
$lang_install['bbthemes_name_fontsize2_name'] = 'Medium font size';
$lang_install['bbthemes_name_fontsize3_name'] = 'Normal font size (post body etc)';
$lang_install['bbthemes_name_fontcolor1_name'] = 'Quote & copyright text';
$lang_install['bbthemes_name_fontcolor2_name'] = 'Code text colour';
$lang_install['bbthemes_name_fontcolor3_name'] = 'Main table header text colour';
$lang_install['bbthemes_name_span_class1_name'] = '';
$lang_install['bbthemes_name_span_class2_name'] = '';
$lang_install['bbthemes_name_span_class3_name'] = '';

$lang_install['bbtopics_topic_title'] = 'Bienvenue &agrave; Evo Cms!';

$lang_install['bbxdata_fields_field_name_icq'] = 'ICQ Num&eacute;ro';
$lang_install['bbxdata_fields_field_name_aim'] = 'AIM Adresse';
$lang_install['bbxdata_fields_field_name_msn'] = 'MSN Messenger';
$lang_install['bbxdata_fields_field_name_yim'] = 'Yahoo Messenger';
$lang_install['bbxdata_fields_field_name_website'] = 'Site Web';
$lang_install['bbxdata_fields_field_name_location'] = 'Location';
$lang_install['bbxdata_fields_field_name_occupation'] = 'Travail';
$lang_install['bbxdata_fields_field_name_interests'] = 'Int&ecirc;ret';
$lang_install['bbxdata_fields_field_name_signature'] = 'Signature';

$lang_install['blocks_bkey_Main_Menu'] = 'Menu Principal';
$lang_install['blocks_bkey_Administration'] = 'Administration';
$lang_install['blocks_bkey_Search'] = 'Recherche';
$lang_install['blocks_bkey_Survey'] = 'Sondage';
$lang_install['blocks_bkey_Information'] = 'Information';
$lang_install['blocks_bkey_User_Info'] = 'Info Utilisateur';
$lang_install['blocks_bkey_Nuke_Evolution'] = 'Evo Cms';
$lang_install['blocks_bkey_Hacker_Beware'] = 'Hacker Beware';
$lang_install['blocks_bkey_Top_10_Downloads'] = 'Top 10 T&eacute;l&eacute;chargement';
$lang_install['blocks_bkey_Top_10_Links'] = 'Top 10 Liens';
$lang_install['blocks_bkey_Forums'] = 'Forums';
$lang_install['blocks_bkey_Submissions'] = 'Soumissions';
$lang_install['blocks_bkey_Link_to_us'] = 'Link to us';
$lang_install['blocks_bkey_Donations'] = 'Dons';

$lang_install['config_slogan'] = 'Votre slogan ici';
$lang_install['config_foot1'] = '<a href="modules.php?name=Spambot_Killer" target="_blank">Spambot Killer</a><br /><a href="modules.php?name=Site_Map" target="_blank"><strong>Site Map</strong></a><br />';
$lang_install['config_foot2'] = '<a href="rss.php?feed=news" target="_blank"><img border="0" src="images/powered/feed_20_news.png" width="94" height="15" alt="[News Feed]" title="News Feed" /></a> <a href="rss.php?feed=forums" target="_blank"><img border="0" src="images/powered/feed_20_forums.png" width="94" height="15" alt="[Forums Feed]" title="Forums Feed" /></a> <a href="rss.php?feed=downloads" target="_blank" /><img border="0" src="images/powered/feed_20_down.png" width="94" height="15" alt="[Downloads Feed]" title="Downloads Feed" /></a> <a href="rss.php?feed=weblinks" target="_blank"><img border="0" src="images/powered/feed_20_links.png" width="94" height="15" alt="[Web Links Feed]" title="Web Links Feed" /></a>  <a href="http://htmlpurifier.org/"><img src="images/powered/html_purifier_powered.png" alt="Powered by HTML Purifier" border="0" /></a> <a href="http://tool.motoricerca.info/robots-checker.phtml?checkreferer=1" target="_blank"><img border="0" src="images/powered/valid-robots.png" width="80" height="15" alt="[Validate robots.txt]" title="Validate robots.txt" /></a><br />';
$lang_install['config_foot3'] = 'Traduit par Adrien Soumy';
$lang_install['config_anonymous'] = 'Anonyme';
$lang_install['config_backend_title'] = 'Evo Cms Powered Site';
$lang_install['config_notify_subject'] = 'NEWS pour mon site';
$lang_install['config_notify_message'] = 'Hey! You got a new submission for your site.';

$lang_install['cnbya_config_tos_text'] = 'Ceci est votre TOS par d&eacute;fault. Vous pouvez l\'editer dans votre panneau d\'administration admin.';

$lang_install['donators_config_block_message'] = 'Vous trouvez ce site bien ? Faite un petit don pour nous aider.';
$lang_install['donators_config_gen_donation_name'] = 'Site Donation';
$lang_install['donators_config_gen_currency'] = 'USD';
$lang_install['donators_config_gen_date_format'] = 'd/m/Y';
$lang_install['donators_config_gen_thank_message'] = 'Merci pour votre g&eacute;n&eacute;reuse donnation!<br /><br />Merci de recommencer!';
$lang_install['donators_config_gen_cancel_message'] = 'D&eacute;sol&eacute; vous n\'avez pas pu donner!<br /><br />Merci de recommencer!';

$lang_install['downloads_categories_title'] = 'G&eacute;n&eacute;ral';
$lang_install['downloads_categories_cdescription'] = 'Categories G&eacute;n&eacute;ral cr&eacute;&eacute;e pendant l\'installation';

$lang_install['evo_userinfo_good_afternoon'] = 'Bonne Apr&agrave;s-midi';
$lang_install['evo_userinfo_username'] = 'Pseudo';
$lang_install['evo_userinfo_show_ip'] = 'Voir IP';
$lang_install['evo_userinfo_avatar'] = 'Avatar';
$lang_install['evo_userinfo_personal_message'] = 'Message Personnel';
$lang_install['evo_userinfo_rank'] = 'Rang';
$lang_install['evo_userinfo_mostever'] = 'Plus &eacute;lev&eacute;';
$lang_install['evo_userinfo_language'] = 'Langage';
$lang_install['evo_userinfo_Break'] = 'Break';
$lang_install['evo_userinfo_pms'] = 'PMs';
$lang_install['evo_userinfo_themes'] = 'Th&egrave;mes';
$lang_install['evo_userinfo_login'] = 'Connect&eacute;/D&eacute;connect&eacute;/s\'enregistr&eacute;';
$lang_install['evo_userinfo_members'] = 'Membres';
$lang_install['evo_userinfo_online'] = 'En ligne';
$lang_install['evo_userinfo_users'] = 'Utilisateur';
$lang_install['evo_userinfo_posts'] = 'Posts';

$lang_install['evo_userinfo_addons_good_afternoon_message'] = 'Bonjour %name%:';
$lang_install['evo_userinfo_addons_personal_message_message'] = '<div align="center">Salut %name%, <br />Bienvenue &agrave; %site%.</div>';

$lang_install['evolution_censor_words'] = 'ass asshole arse bitch bullshit c0ck clit cock crap cum cunt fag faggot fuck fucker fucking fuk fuking motherfucker pussy shit tits twat';

$lang_install['links_categories_title'] = 'G&eacute;n&eacute;ral';
$lang_install['links_categories_cdescription'] = 'Categories G&eacute;n&eacute;ral cr&eacute;&eacute;e pendant l\'installation';


$lang_install['modules_meta_keywords'] = 'Nuke-Evolution, evo, pne, evolution, nuke, php-nuke, software, downloads, community, forums, bulletin, boards, cms, nuke-evo, phpnuke';

$lang_install['modules_title_Advertising'] = 'Publicit&eacute;';
$lang_install['modules_title_Content'] = 'Contenu';
$lang_install['modules_title_Docs'] = 'Docs';
$lang_install['modules_title_Donations'] = 'Dons';
$lang_install['modules_title_Downloads'] = 'T&eacute;l&eacute;chargements';
$lang_install['modules_title_FAQ'] = 'FAQ';
$lang_install['modules_title_Feedback'] = 'R&eacute;action';
$lang_install['modules_title_Forums'] = 'Forums';
$lang_install['modules_title_Groups'] = 'Groupes';
$lang_install['modules_title_News'] = 'News';
$lang_install['modules_title_NukeSentinel'] = 'NukeSentinel';
$lang_install['modules_title_Private_Messages'] = 'Messages Priv&eacute;';
$lang_install['modules_title_Profile'] = 'Profil';
$lang_install['modules_title_Recommend_Us'] = 'Recommandez-nous';
$lang_install['modules_title_Reviews'] = 'Critiques';
$lang_install['modules_title_Search'] = 'Recherche';
$lang_install['modules_title_Site_Map'] = 'Site Map';
$lang_install['modules_title_Spambot_Killer'] = 'Spambot Killer';
$lang_install['modules_title_Statistics'] = 'Statistiques';
$lang_install['modules_title_Stories_Archive'] = 'Archive des histoires';
$lang_install['modules_title_Submit_News'] = 'Soumettre une News';
$lang_install['modules_title_Supporters'] = 'Support&egrave;res';
$lang_install['modules_title_Surveys'] = 'Sondage';
$lang_install['modules_title_Top'] = 'Top';
$lang_install['modules_title_Topics'] = 'Sujets';
$lang_install['modules_title_Web_Links'] = 'Web Links';
$lang_install['modules_title_Your_Account'] = 'Votre compte';

$lang_install['modules_cat_Home'] = 'Accueil';
$lang_install['modules_cat_Members'] = 'Membres';
$lang_install['modules_cat_Community'] = 'Communaut&eacute;e';
$lang_install['modules_cat_Statistics'] = 'Statistiques';
$lang_install['modules_cat_Files_Links'] = 'Files&nbsp;&amp;&nbsp;Links';
$lang_install['modules_cat_News'] = 'News';
$lang_install['modules_cat_Other'] = 'Autres';


$lang_install['modules_links_title'] = 'Accueil';

$lang_install['poll_data_optionText_1'] = 'Ummmm, pas mal';
$lang_install['poll_data_optionText_2'] = 'Cool';
$lang_install['poll_data_optionText_3'] = 'Terrifiant';
$lang_install['poll_data_optionText_4'] = 'Le meilleur!';
$lang_install['poll_data_optionText_5'] = 'Qu\'est ce que sait que sa?';
$lang_install['poll_data_optionText_6'] = '';
$lang_install['poll_data_optionText_7'] = '';
$lang_install['poll_data_optionText_8'] = '';
$lang_install['poll_data_optionText_9'] = '';
$lang_install['poll_data_optionText_10'] = '';
$lang_install['poll_data_optionText_11'] = '';
$lang_install['poll_data_optionText_12'] = '';

$lang_install['poll_data_pollTitle'] = 'Que pensez-vous de notre site?';
$lang_install['poll_data_planguage'] = 'french';

$lang_install['quotes_quote'] = 'Nos morituri te salutamus - CBHS';

$lang_install['reviews_categories_title'] = 'G&eacute;n&eacute;ral';
$lang_install['reviews_categories_cdescription'] = 'Categories G&eacute;n&eacute;ral cr&eacute;&eacute;e pendant l\'installation';

$lang_install['stories_title'] = 'Bienvenue &agrave; Evo-Cms';
$lang_install['stories_hometext'] = 'Bienvenue &agrave; Evo-Cms.<br /><br />You must now setup an admin account.  You can do this by <a href="admin.php">clicking here</a>.<br /><br /><br /><br /><strong>NOTE:</strong> You can remove this by going into the News Administration or by clicking the delete button below.';
$lang_install['stories_cat_Articles'] = 'Articles';

$lang_install['themes_custom_name'] = 'Chromo';

$lang_install['topics_text'] = 'EVO CMS';
$lang_install['topics_name'] = 'evolution';

$lang_install['users_name_Anonymous'] = 'Anonyme';
$lang_install['users_timezone_Anonymous'] = '1.00';
$lang_install['users_lang_Anonymous'] = 'french';
$lang_install['users_dateformat_Anonymous'] = 'D M d, Y g:i a';
?>