<?php
/*=======================================================================
 Nuke-Evolution   :   Enhanced Web Portal System
 ========================================================================

 Nuke-Evo Base          :   #$#BASE
 Nuke-Evo Version       :   #$#VER
 Nuke-Evo Build         :   #$#BUILD
 Nuke-Evo Patch         :   #$#PATCH
 Nuke-Evo Filename      :   #$#FILENAME
 Nuke-Evo Date          :   #$#DATE
 Nuke-Evo Author        :   ReOrGaNiSaTiOn

 Copyright (c) 2010 by The Nuke-Evolution Development Team
 ========================================================================

 LICENSE INFORMATIONS COULD BE FOUND IN COPYRIGHTS.PHP WHICH MUST BE
 DISTRIBUTED WITHIN THIS MODULEPACKAGE OR WITHIN FILES WHICH ARE
 USED FROM WITHIN THIS PACKAGE.
 IT IS 'NOT' ALLOWED TO DISTRIBUTE THIS MODULE WITHOUT THE ORIGINAL
 COPYRIGHT-FILE.
 ALL INFORMATIONS ABOVE THIS SECTION ARE 'NOT' ALLOWED TO BE REMOVED.
 THEY HAVE TO STAY AS THEY ARE.
 IT IS ALLOWED AND SHOULD BE DONE TO ADD ADDITIONAL INFORMATIONS IN
 THE SECTIONS BELOW IF YOU CHANGE OR MODIFY THIS FILE.

/*****[CHANGES]**********************************************************
-=[Base]=-
-=[Mod]=-
 ************************************************************************/

// General entries were no UTF-8 is accepted
$lang_install['Next']  = 'NEXT STEP';
$lang_install['Back']  = 'LAST STEP';
$lang_install['Restart']  = 'RESTART';
$lang_install['Help']  = 'HELP';
$lang_install['IMG_OK']  = 'Check is ok';
$lang_install['IMG_BAD']  = 'Check failed';
$lang_install['IMG_WARN']  = 'Only Warning, no error';
$lang_install['IMG_DONE']  = 'Done';

// General entries with UTF-8 support
$lang_install['Langcode'] = 'en-us';
$lang_install['Landdir']  = 'ltr';
$lang_install['No']  = 'No';
$lang_install['Yes']  = 'Yes';

$lang_install['Head_Title'] = 'Installation';
$lang_install['Block_Title'] = 'Status';
$lang_install['Block_Step_0'] = 'Welcome';
$lang_install['Block_Step_1'] = 'Infos';
$lang_install['Block_Step_2'] = 'File-Configuration';
$lang_install['Block_Step_3'] = 'DB-Configuration';
$lang_install['Block_Step_4'] = 'DB-Installation';
$lang_install['Block_Step_5'] = 'Base Settings';
$lang_install['Block_Step_6'] = 'Admin Account';
$lang_install['Block_Step_7'] = 'DB-Basesettings';
$lang_install['Block_Step_8'] = 'Finished';
$lang_install['Block_Step_9'] = 'Log';

// Help-System
if (!defined('_EVO_HELPSYSTEM')) {
    define('_EVO_HELPSYSTEM', 'Evo Help');
}

// Step Welcome
$lang_install['Welcome'] = 'Congratulations<br/><br/>You are going to install >> '.$var_install['version'].' <<<br/>This installation procedure will guide you through some information needed for the installation, perform some tests and will configure the base settings for you';
$lang_install['Language_Select'] = 'If you do not have a choice for another language in the selection box, then you did not copy your language from the language folder of the downloaded Evo files onto your server.';
$lang_install['License_Header'] = 'Please read this License Agreement carefully and submit your agremment with it';
$lang_install['License_Agreement'] = 'To continue with this Installation means, you have accepted this License Agreement.';
$lang_install['License_Text'] = '
                      I M P O R T A N T    N O T E
           --------------------------------------------------
   PLEASE READ AND ACCEPT THE FOLLOWING USER AGREEMENT IF YOU ARE USING
   THIS SOFTWARE PACKAGE OR ANY OF ITS CONTENT. THANKS:

   01. All copyright, credit and display notices used within this
       package must remain intact.

   02. All copyright, credit and display notices generated by this
       package must remain intact.

   03. All copyright, credit and display notices must remain visible
       and must remain intact in all locations.

   04. Modification and alteration of this package is done at the users
       own risk. This must only be done in compliance with all visual,
       internal display, modification and distribution terms.

   05. To ensure authenticity when downloading any material related to
       Nuke-Evolution Basic, download all / any material from the
       official mirror sites stated below. Material downloaded from
       non-official sources may contain malicious content and is not
       supported in any way by Nuke-Evolution Basic, the
       Nuke-Evolution Team or any of the authors of Nuke-Evolution
       material including authors of included scripts and authors of
       the CMS engine:

       - http://www.nuke-evolution.com

   06. All mods, blocks, modules, themes, code that was not explicitly
       created by the Nuke-Evolution team has been credited to the
       original author.

   07. Official support for every aspect of the project will only be
       provided by the Nuke-Evolution website.

       - http://www.evo-german.com

   08. For further license information please read the gpl text file
       include in "licenses and credits\Licenses\GPL"
  ======================================================================*/


 WARRANTY:
 ---------

 Because Nuke-Evolution Basic is licensed free of charge, there is no
 warranty for the package, to the extent permitted by applicable law.
 Except when otherwise stated in writing, the Nuke-Evolution Team
 provides Nuke-Evolution "as is" without warranty of any kind, either
 expressed or implied, including, but not limited to, the implied
 warranties of merchantability and fitness for a particular purpose.
 The entire risk as to the quality and performance of the package is
 with you. Should the package prove defective, you assume the cost of
 all necessary servicing, repair or correction.';

// Step Infos
$lang_install['Infos_Title'] = 'We have checked your system.<br />Below you find the information we found and if there are any warnings or errors.<br />';
$lang_install['DB_Setup'] = 'In this step, we initialize the database connection.<br />All necessary information should be available from your provider, or you should have defined them by yourself at the time you created the database<br />';

// Language entries for Installer
$lang_install['Date']    = 'Date';
$lang_install['Step']    = 'Step';
$lang_install['Last_Step']    = 'Last Step';
$lang_install['Log_Message']    = 'Message';
$lang_install['Submit'] = 'Submit values';

$lang_install['Installation_started'] = 'Installation started';
$lang_install['Server_Configuration_Details'] = 'Server Configuration Details';
$lang_install['Server_Configuration_Summary'] = 'Server Configuration Summary';
$lang_install['DB_Installation'] = 'Creating Database Tables';
$lang_install['Installation_Start_failed'] = 'We found critical errors, which makes it unlikely Nuke-Evolution can run without problems on your server.<br />Click on "Help" to read our Wiki, there you will find, which Base settings we need to run a proper installation.<br />Tips, Tricks and recommended Hosts, that Nuke-Evolution runs on, can be found in our Forum.';
$lang_install['Errors_found'] = 'Errors we found';
$lang_install['Warnings_found'] = 'Warnings we found';

$lang_install['File_Setup'] = 'File Configuration';
$lang_install['File_error'] = 'Error: The file is not available.';
$lang_install['File_warning'] = 'Warning: The file is not available.';
$lang_install['File_notchanged'] = 'Warning: Permissons are not correct';
$lang_install['File_mustexist'] = 'File must exist - but isn\'t present. That\'s an error. Please see helptext for file/directory location and check if you have uploaded the file/directory';
$lang_install['File_shouldexist'] = 'File should exist - but isn\'t present. That\'s no error because the file is optional. Please see helptext for file/directory location.';
$lang_install['File_done'] = 'Ok: Permissions are set correct';
$lang_install['File_htaccess'] = 'File: .htacess';
$lang_install['File_Help_htaccess'] = 'File: .htacess<br />Path: root<br />This file is an extension of the Webserver configuration file with directives for the Webserver. In restricted Environments this file could cause a Webserver Error so we deliver it as evo.htaccess. You can try to rename the file to .htaccess. If you then get an Webserver Error rename the file again to evo.htaccess and you can continue with the installation.';
$lang_install['File_staccess'] = 'File: .staccess';
$lang_install['File_Help_staccess'] = '';
$lang_install['File_ultramode'] = 'File: Ultramode';
$lang_install['File_Help_ultramode'] = '';
$lang_install['File_errorlog'] = 'File for error logging';
$lang_install['File_Help_errorlog'] = 'File: error.log<br />Path: includes/log/<br />In this file all not administrative warnings or errors are logged. If the file hasn&#039;t the correct write permission, no logging occurs.';
$lang_install['File_adminlog'] = 'File for logging administration messages';
$lang_install['File_Help_adminlog'] = 'File: admin.log<br />Path: includes/log/<br />In this file all administration warnings or errors are logged. If the file hasn&#039;t the correct write permission, no logging occurs.';
$lang_install['File_ForumsCacheDir'] = 'Directory: Forum Cache';
$lang_install['File_Help_ForumsCacheDir'] = '';
$lang_install['File_FilesDir'] = 'Directory: Forum File Up-/Download';
$lang_install['File_Help_FilesDir'] = '';
$lang_install['File_FilesThumbDir'] = 'Directory: Forum Thumbnails';
$lang_install['File_Help_FilesThumbDir'] = '';
$lang_install['File_AvatarDir'] = 'Directory: Avatars';
$lang_install['File_Help_AvatarDir'] = '';
$lang_install['File_LangBBCode'] = 'File: Languagefile for BBCode';
$lang_install['File_Help_LangBBCode'] = '';
$lang_install['File_LangFAQ'] = 'File: Languagefile for FAQ';
$lang_install['File_Help_LangFAQ'] = '';
$lang_install['File_LangFAQAttach'] = 'File: Languagefile for FAQ Attachements';
$lang_install['File_Help_LangFAQAttach'] = '';
$lang_install['File_LangRules'] = 'File: Languagefile for Forumrules';
$lang_install['File_Help_LangRules'] = '';
$lang_install['File_ForumModules'] = 'Directory: Forummoduls';
$lang_install['File_Help_ForumModules'] = '';
$lang_install['File_ForumModulesCache'] = 'Directory: Forummodules Cache';
$lang_install['File_Help_ForumModulesCache'] = '';
$lang_install['File_ForumModulesCacheExplain'] = 'Directory: Forummodule Cache Explainations';
$lang_install['File_Help_ForumModulesCacheExplain'] = '';
$lang_install['File_SupportersImagesSupporters'] = 'Directory: Supporter Banner';
$lang_install['File_Help_SupportersImagesSupporters'] = '';
$lang_install['File_IncludesCache'] = 'Directory: Cachedirectory';
$lang_install['File_Help_IncludesCache'] = '';
$lang_install['File_IncludesCacheFile'] = 'File: Cachefile';
$lang_install['File_Help_IncludesCacheFile'] = '';
$lang_install['File_HTMLPurifierDecorator'] = 'Directory: HTML-Purifier Decorator';
$lang_install['File_Help_HTMLPurifierDecorator'] = '';
$lang_install['File_HTMLPurifierSerializer'] = 'Directory: HTML-Purifier Serializer';
$lang_install['File_Help_HTMLPurifierSerializer'] = '';
$lang_install['File_HTMLPurifierSerializerHtml'] = 'Directory: HTML-Purifier Serializer HTML';
$lang_install['File_Help_HTMLPurifierSerializerHtml'] = '';
$lang_install['File_IconModDefIcons'] = 'File: Icon Mod defined Icons';
$lang_install['File_Help_IconModDefIcons'] = '';
$lang_install['File_Configdb'] = 'File: DB Configuration file';
$lang_install['File_Help_Configdb'] = '';
$lang_install['Downloads_Files_Dir'] = 'Directory: Downloads Files';
$lang_install['Downloads_Files_Dir_Help'] = '';
$lang_install['File_CantOpen'] = 'Cannot open file';
$lang_install['File_CantWrite'] = 'Cannot write file';
$lang_install['File_CantChange'] = 'The Permissions of the file couldn&#039;t be changed';
$lang_install['File_ErrorChmod'] = 'Some important files have wrong file permissions<br />We tried to change them, but aren&#039;t allowed to do.<br />You now can either change the file permissions by yourself or let us do this by FTP Connect.<br />If you want to do it by yourself, you find within the helptextes for every file were it&#039;s located. After you have done this, restart the Installation.<br />For those, which doesn&#039;t want to do this by themselves, you can klick on the submit button below. You then will be asked for a valid FTP Account. After this step is completed, restart the Installation.';
$lang_install['File_FTPChmod'] = 'Start change permissions by FTP';
$lang_install['FTP_Configuration_Details'] = 'FTP Configuration';
$lang_install['FTP_User'] = 'FTP Username';
$lang_install['FTP_Pwd'] = 'FTP Password';
$lang_install['FTP_Host'] = 'FTP Host';
$lang_install['FTP_Path'] = 'FTP Path';
$lang_install['FTP_Port'] = 'FTP Port';
$lang_install['FTP_Help_User'] = 'Here you have to insert the FTP User Account you used to upload files onto the server.<br />As default value we show you the user which is owner of the files on your Webserver.';
$lang_install['FTP_Help_Pwd'] = 'Here you have to insert the Password for the FTP User Account.';
$lang_install['FTP_Help_Host'] = 'The Domain or IP-Adress of your host were we have to connect with.<br />Here you have to insert the same values as you did into your FTP Software.';
$lang_install['FTP_Help_Port'] = 'Here you have to insert the port on which the FTP Service is running on your Server. Normally this is Port:21. You can use here the same settings as you use inside your FTP Software. If there is no entry, you can leave default port.';
$lang_install['FTP_Help_Path'] = 'The Path were the Evo Installation is located onto your server.<br />Please add here the way you have to go after your login by FTP. That means, you have to add the way to the subdirectory to your Installation if there is one.<br />If you didn&#039;t install inside a subdirectoy, you can leave this field empty.';
$lang_install['FTP_Error_Host'] = 'We can&#039;t connect to the server. Please check if you entered the same informations as you did for your FTP Server.';
$lang_install['FTP_Error_Login'] = 'Either FTP Username or Password is wrong. Please check if you entered the same informations as you did for your FTP Server.';

$lang_install['DB_Host'] = 'Hostname';
$lang_install['DB_Help_Host'] = 'Name of the Database Server. Normally \'localhost\', which is used from us as default. You can use the IP Address to, which will reduce DNS lookups.';
$lang_install['DB_Name'] = 'Name of the database';
$lang_install['DB_Help_Name'] = 'Name of the Database<br />Either the Database was created through your Provider (in this case you should have got the name from your Provider) or you have created the database yourself (in this case we need the name you gave your database on creation).';
$lang_install['DB_Username'] = 'Connection Username';
$lang_install['DB_Help_Username'] = 'Database Username<br />The Username used to connect to the Database.<br />Either you got this name from your Provider or you created this Database account by yourself.';
$lang_install['DB_Password'] = 'Connection Password';
$lang_install['DB_Help_Password'] = 'Connection Password<br />The Password needed to connect to the Database.<br />Either you got this password from your Provider or you defined this password by yourself when you created the database user.';
$lang_install['DB_Type'] = 'Database Type';
$lang_install['DB_Help_Type'] = 'Database Type<br />The Type of your Database. We have checked your System. All available Database Types could be selected.';
$lang_install['DB_Prefix'] = 'Table prefix (Standard: evo)';
$lang_install['DB_Help_Prefix'] = 'Table prefix<br />Every Table must have a unique name inside the database. Because you can use your database for several systems, every System should use an own prefix. Means an unique string which is added to the table name. Standard for our system is \'evo_\'. Means, that every table we create or use will begin with \'evo_\'.';
$lang_install['DB_Conf_wrong'] = 'We could not establish a connection to the database server.<br />Please check your entries and try again';
$lang_install['DB_DB_wrong'] = 'We could establish a connection to the database server, but not to your database.<br />Please check your entries and try again';
$lang_install['DB_Conf_ok'] = 'We could establish a connection to your database.<br />Your entries were ok.';
$lang_install['DB_Prefix_exists'] = 'There are existing Tables with the same prefix.';
$lang_install['DB_Delete_Existing'] = 'Should we overwrite/delete those existing tables';
$lang_install['DB_Help_Delete_Existing'] = 'Tables delete/overwrite<br />We found Tables in your database either from an old installation or you have selected a prefix which allready is in use from another system.<br />With \'No\', we do not delete those existing Tables. We check, if all needed fields and indexes are available. If not we add or change them.<br />With \'Yes\' we delete the old tables and create them new. This is the safest method for a proper running system.';
$lang_install['DB_Help_Update_Existing'] = 'Existing Connection found<br/>We found an existing configuration file. With the informations included, we could establish a connection to the database.<br />It seems, that this could be an update rather than a fresh installation.<br />If you select \'update\' we only check existing tables and change them to new configuration or add not existing tables.';
$lang_install['DB_Update_Existing'] = 'Is this an update of an existing installation or a fresh install';
$lang_install['DB_Update_Question'] = 'It seems, that this is an upgrade, rather than a fresh installation. Please submit the way, the installer should handle this installation.';
$lang_install['DB_Help_Update_Convert'] = 'Normally, all older systems did use Characterset ISO-8859-1. Nuke-Evo > 2.1.0 uses UTF-8, a multibyte international Characterset. If you select YES, we convert all textfields in the database to UTF-8.';
$lang_install['DB_Update_Convert'] = 'Shell we convert characterset ISO-8859-1 to UTF-8 ?';
$lang_install['DB_Update'] = 'Update';
$lang_install['DB_No_Convertion'] = 'No Convertion';
$lang_install['DB_Convert'] = 'Convertion';
$lang_install['DB_Installation'] = 'New Installation';
$lang_install['DB_Upgrade'] = 'Database Upgrade';
$lang_install['DB_Help_DiffUserPrefix'] = 'Different prefix for usertables<br />Your existing configuration shows different tableprefixes. This installer doesn\'t support differente prefixes. You can rename your user_table and user_temp_table to fit the prefix for the other tables. Then restart the installer and select \'YES\' on the question if the Installer should change the user_prefix. After the installation you can again rename your user_table and user_temp_table to your old prefix. You have to change your config.php too.';
$lang_install['DB_DiffUserPrefix'] = 'Do you want the Installer change the prefix for your usertables';
$lang_install['DB_DiffUserPrefixMore'] = 'Your existing confguration shows different prefixes for your DB-Tables.<br />If you select \'YES\', the Intallser will try to rename your tables to fit one prefix for all tables. If you select \'NO\', the installation can\'t be continued by the installer.<br />Klick our help image for more informations.';
$lang_install['DB_Table_Exists'] = 'Table exists';
$lang_install['DB_Table_NotExists'] = 'Table must be created';
$lang_install['DB_Table_Done'] = 'Table successfull created';
$lang_install['DB_Table_Warning_override'] = 'You have choosen to override existing tables. All data inside them will be lost !!<br />You can go back or Restart the Installation if this was a wrong decision.';
$lang_install['DB_Table_Create_in_process'] = 'Table creation in process .... do not interrupt !!';
$lang_install['DB_Table_Deleted'] = 'Table deleted';
$lang_install['DB_Table_Created'] = 'Table created';
$lang_install['DB_Table_Checked'] = 'Table checked';
$lang_install['DB_Table_Identical'] = 'Table is identical to new install table settings';
$lang_install['DB_Table_Changed'] = 'Table is changed to fit new install table settings';
$lang_install['DB_Table_Created_not'] = 'Table couldn\'t be created. Heavy error.';
$lang_install['DB_Table_Changed_not'] = 'Table couldn\'t be changed. Heavy error';
$lang_install['DB_Table_Created_ready'] = 'Table installation has finished<br />There is, -as far as we know- no errors that occured.<br />Within the next step you configure your System to work.';
$lang_install['DB_Table_Created_ready_error'] = 'Table installation has finished<br />Some errors occured.<br />Please check the log to see what happened.';
$lang_install['DB_Entry_Update_missed'] = 'We received an error on insertion into the database';
$lang_install['DB_RenameUserTableFail'] = 'We couldn\'t rename your user tables';

// Language entries for Checks
$lang_install['Found_language'] = 'We detected you use this language';
$lang_install['Found_language_change'] = 'If you want to change this language (which will be the base language for your website), you can choose between the languages we found';

$lang_install['SystemInfo'] = 'System Informations';
$lang_install['Sysname']    = 'Operating System';
$lang_install['SysNodename']= 'Name of the Server';
$lang_install['SysDomain']  = 'Server Domain';
$lang_install['SysRelease'] = 'Operating System Release';
$lang_install['SysVersion'] = 'Operating System Version';
$lang_install['SysMachine'] = 'Processor Architecture';
$lang_install['SystemUserInfo']     = 'System User Information';
$lang_install['SysUser']            = 'System User';
$lang_install['SysUserProcessID']   = 'System User ID';
$lang_install['SysUserProcessName'] = 'System User Name';
$lang_install['SysGroup']           = 'System Group Information';
$lang_install['SysGroupProcessID']  = 'System Group ID';
$lang_install['SysGroupProcessName']= 'System Group Name';

$lang_install['FreeDiskSpace']      = 'Free Diskspace';
$lang_install['No_Free_Disk_Space'] = 'We got no information about your free Diskspace. Please check if enough is evailable (> 50 MB).';
$lang_install['Safe_Mod']    = 'Safe Mode';
$lang_install['SafeMod_On']    = 'Safe Mode is activated.<br />This could cause erros in any action which requires filehandling (a.e.: Cache, Fileupload)';
$lang_install['PHP_Version']    = 'PHP_Version';
$lang_install['Wrong_PHP_Version'] = 'Your PHP-Version is too old. We do not support this version any longer.';
$lang_install['Unsafe_PHP_Version'] = 'Your PHP-Version is too old. We support this version, but we recommend an update, because your site could be easily hacked.';
$lang_install['Register_Globals']    = 'Register Globals';
$lang_install['Register_Globals_On'] = 'Register Globals are enabled on your Server.<br />OK, we check our variables in Nuke-Evo, but this is a security issue for Blocks, Modules and AddOns not running our security features.';
$lang_install['Captcha_enabled'] = 'Captcha available';
$lang_install['Open_Basedir'] = 'Open Basedir';
$lang_install['Open_Basedir_On'] = 'Open Basedir is activated and doesn&#039;t allow write access to the files you uploaded by FTP onto your server. FTP User and Group are differtent to the Webserver User and Group.';
$lang_install['Session_Support'] = 'Session Support';
$lang_install['No_Session_Support'] = 'Session Support isn\'t activated<br />Because this is a basic PHP-Modul needed for security reasons, we stop your installation here.';
$lang_install['CURL_Libary'] = 'Curl Library';
$lang_install['No_Curl_Modul'] = 'CURL Modul isn\'t loaded.<br />You cannot open files on linked servers. Some functions will not work in your Installation (a.e. checking for updates).';
$lang_install['File_Upload'] = 'File Upload';
$lang_install['No_FileUploads'] = 'File Upload isn\'t allowed on your server.';
$lang_install['Size_MB'] = 'MB';
$lang_install['Size_GB'] = 'GB';
$lang_install['File_Upload_Maxsize'] = 'Upload maximum Filesize';
$lang_install['Max_FileSize_ToSmall'] = 'The allowed uploadsize for files is to small. So we stop here your installation.';
$lang_install['Max_FileSize_Small'] = 'The allowed uploadsize for files is very small. It will limit the size of images and files for upload onto your server.';
$lang_install['SMTP_enabled'] = 'SMTP enabled';
$lang_install['SMTP_host'] = 'SMTP Host';
$lang_install['SMTP_sender'] = 'STMP Sender';
$lang_install['SMTP_command'] = 'STMP command';
$lang_install['FTP_enabled'] = 'FTP enabled';
$lang_install['Max_Post_Size'] = 'Maximum size of postings';
$lang_install['Mod_Rewrite'] = 'Mod Rewrite (Important for Lazy Google Tab)';
$lang_install['Mod_Rewrite_no'] = 'You can not use Lazy Google Tab, because "mod_rewrite" is disabled in your system';
$lang_install['Mod_Rewrite_no_check'] = 'We couldn\'t check if mod_rewrite is enabled. So it can be possible, that you cannot use Lazy Google Tab.';
$lang_install['GD_Libary'] = 'GD Library';
$lang_install['GD_Libary_JPEG'] = 'GD Library - JPEG Support (Important for Captcha)';
$lang_install['Memory_Limit'] = 'Memory Limit to be used';
$lang_install['Memory_Limit_not'] = 'Your Memory Limit is not set. This means, that a program can use the whole memory of your system (limited to 128 MB). Mostly important for Downloads. They can slow down your system for other users.';

// Language entries Base Configuration
$lang_install['Base_Setup'] = 'Basic Settings<br />Here you define the important basic settings of your System.<br />All settings can be changed in your System Administration after your Site is up and running';
$lang_install['Base_Sitename'] = 'Site Name';
$lang_install['Base_Help_Sitename'] = 'The name of your website.<br />Max. 200 characters.<br />Will be shown in the headline of the Browser and inside the Forum. Even too it is used as Meta-Tag in the header of your site (a.e. for searchengines)';
$lang_install['Base_Sitename_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Base_Sitedescription'] = 'Site Description (max. 200 characters)';
$lang_install['Base_Help_Sitedescription'] = 'A short description of your Site. Will be shown to users too';
$lang_install['Base_Descriptione_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Base_Url'] = 'URL of your Website (without http://)';
$lang_install['Base_Help_Url'] = 'The Domain of your Website. Example: www.mydomain.com';
$lang_install['Base_Url_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Base_Server_Port'] = 'Port of the webserver.';
$lang_install['Base_Help_Server_Port'] = 'Port of the webserver.<br />Number: 5-digits.<br />The port on your server where your webserver is listening. Normally: 80 or behind a proxy: 8080.';
$lang_install['Base_Server_Port_wrong_entry'] = 'The Serverport must be greater or equal than 80 and smaller than 65535';
$lang_install['Base_Server_Port_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Base_Cookie_Domain'] = 'Cookie Domain';
$lang_install['Base_Help_Cookie_Domain'] = 'Cookie Domain is normally the same Domain as your website.';
$lang_install['Base_Cookie_Name_wrong_chars'] = 'You have uses unallowed characters for your Cookie Domain';
$lang_install['Base_Cookie_Name_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Base_Cookie_Domain_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Base_Cookie_Path'] = 'Cookie Path.';
$lang_install['Base_Help_Cookie_Path'] = 'If you have your Evo-Installation in a subdir of the domain, you have to insert here the piece of the URL behind the Domainname';
$lang_install['Base_Cookie_Path_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Base_Cookie_Name'] = 'Cookie Name';
$lang_install['Base_Help_Cookie_Name'] = 'A unique Name for your Cookie.<br />Inside of your domain, this name must be unique for a cookie.<br />Allowed are numbers and characters only.';
$lang_install['Base_Cookie_Name_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Base_Board_Email'] = 'Email Address of the Webmaster';
$lang_install['Base_Help_Board_Email'] = 'Email Address of the Webmaster.<br />Will be used for all system emails as Sender.<br />In some Systems the email address must be the same as used within the php-ini entries for smtp.';
$lang_install['Base_Board_Email_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Base_Board_Email_Sig'] = 'Email Signature';
$lang_install['Base_Help_Board_Email_Sig'] = 'Email Signature.<br />Max. 200 chars<br />Used in emails or messages as signature.';
$lang_install['Base_Board_Email_Sig_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Base_Board_Default_Lang'] = 'Base Language';
$lang_install['Base_Help_Board_Default_Lang'] = 'Base Language.<br />Base Language for your Website. You can choose between the languages we found on your Nuke-Evo Installation.<br />Could be changed later by Administrator-';
$lang_install['Base_Board_Default_Lang_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Base_Board_Startdate'] = 'Start date of the website';
$lang_install['Base_Help_Board_Startdate'] = 'Start date of the website.<br />Will be used as <strong>official start date</strong> of your website. Normally the install date. If your site is running a longer time or will start in the future, you can change the date here.';
$lang_install['Base_Board_Startdate_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Base_Board_Dateformat'] = 'Standard date format';
$lang_install['Base_Help_Board_Dateformat'] = 'Standard date format.<br />The date format defined here is used for all base system settings.';
$lang_install['Base_Board_Dateformat_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Base_Board_Timezone'] = 'Time zone of your site';
$lang_install['Base_Help_Board_Timezone'] = 'Time zone of your site.<br />Because your website is worldwide available - but your users are living in different timezones<br />all input have to be set in accordance to one defined time zone.<br />This is time zone for your server.<br />Normally not the timezone where you life in, but the timezone your server is running in.';
$lang_install['Base_Board_Timezone_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Base_Conf_wrong'] = 'We found errors in your Base Configuration.<br />Please check your Input.';
$lang_install['Base_Conf_ok'] = 'We cannot find errors in your Base Configuration settings.<br />Within the next step you can create the Administrator for your website.';
$lang_install['Base_From_Update'] = 'You are in Update Mode.<br />The information shown below is gathered from your existing system.';

// Language entries for creating Admin Account
$lang_install['Admin_Setup'] = 'Creating Administration Account';
$lang_install['Admin_Configuration_Details'] = 'Administrator';
$lang_install['Admin_Name'] = 'Username of the Administrator (will be used in all postings, written by this Administrator)';
$lang_install['Admin_Help_Name'] = 'The username of the Administrator wiil be used on every place, normally an username is shown as poster or voter a.s.o.';
$lang_install['Admin_Name_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Admin_Homepage'] = 'Website of the Administrator';
$lang_install['Admin_Help_Homepage'] = 'Website of the Administrator<br />Even too an Administrator is not allowed to vote for his own site. The checks will be done against the entry in this field';
$lang_install['Admin_Homepage_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Admin_Password'] = 'Password';
$lang_install['Admin_Help_Password'] = 'Password<br />The Password should be not smaller than 6 characters and not longer than 25 characters.';
$lang_install['Admin_Password2'] = 'Repeat Password';
$lang_install['Admin_Password_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Admin_Password_not_match'] = 'The Passwords do not match';
$lang_install['Admin_Password_not_match_existing'] = 'The Passwords do not match the existing one from database';
$lang_install['Admin_Help_Password2'] = 'Repeat Password<br />Because it is not easy to change the password for this Site Administrator, you have to repeat the password to be sure you made no typo\'s.';
$lang_install['Admin_Lang'] = 'Language for Administrator';
$lang_install['Admin_Help_Lang'] = 'Language for Administrator.<br />The entry in this field will be used as standard language for this Administrator';
$lang_install['Admin_Lang_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Admin_Create_User'] = 'Do you want to create an user account with the same name ?';
$lang_install['Admin_Help_Create_User'] = 'Create User account<br />For Security reasons you should not create one. But for system handling and maintenance purposes it is easier to have the user identical to the Admin';
$lang_install['Admin_Create_User_no_entry'] = 'This field is not allowed to be empty';
$lang_install['Admin_Conf_wrong'] = 'We found errors in your Administrator Settings.<br />Please check your Input.';
$lang_install['Admin_Conf_ok'] = 'We cannot find errors in your Administrator Settings.<br />With the next step, we fill your database with general base information and the settings you gave us in the previous steps.';

// Language entries for Database Step
$lang_install['Base_Information_Setup'] = 'Fill Database with Basic Settings';
$lang_install['Base_Information_Details'] = 'Tables in your database';
$lang_install['Base_Informations_NoNeed'] = 'No information to add into database';
$lang_install['Base_Informations_ToDo'] = 'Information for inserting available';
$lang_install['Base_Informations_Done'] = 'Information already inserted';
$lang_install['Base_Informations_ready'] = 'The Base Settings are inserted in your database.<br />There is -as we can checked- no errors.<br />You have finished your Installation successfully.';
$lang_install['Base_Informations_in_process'] = 'Inserting Base Settings ... please do not interrupt !!';
$lang_install['Base_Information_DB_Success'] = 'Base Settings successfully inserted into database';
$lang_install['Base_Informations_ready_error'] = 'We found errors during insertion into the database.<br />Please check your installation.<br />You have finished your Installation with errors.';

// Language entries for Last Step
$lang_install['Information_Setup_Ready'] = 'Congratulations!<br />You have finished your configuration.';
$lang_install['Information_Setup_Ready_allok'] = 'We recognized no errors during the installation process.<br/>This means, that your website is now configured and ready for use.';
$lang_install['Information_Setup_Ready_nostep'] = 'Not all Installation steps have been done.<br />For the steps done, we found no errors.<br />If your website is running, is a thing we cannot say. You have to check it and run the installer again if there are errors.';
$lang_install['Information_Setup_Ready_error'] = 'We recognized heavy errors.<br />We recommend you check the log and restart the installation.';
$lang_install['Information_Setup_Ready_noinfo'] = 'We do not have any information on the installation process.<br />Means, we cannot say anything: If there are errors, if tables were created.<br />We recommend restarting the installation process.';
$lang_install['Information_Setup_GoHome'] = 'Go to your new Homepage';
$lang_install['Information_Setup_GoAdmin'] = 'Go to the Admin panel of your new Website';
$lang_install['Donate'] = 'This Software was developed in our free time. Please honor our work with a donation.';

// Language entries for Database fields

$lang_install['Page_Top']    = 'Page Top';
$lang_install['Left_Block']  = 'Left Block';
$lang_install['Page_Bottom'] = 'Page Bottom';
$lang_install['Group_Administrators'] = 'Administrators';
$lang_install['Group_Moderators'] = 'Moderators';

$lang_install['bbboard_message_1'] = 'This message is shown on all pages and to all users and stretched to 80% of the available width.';
$lang_install['bbboard_message_2'] = 'This message is shown only on the index page and is only visible for registered users.';

$lang_install['bbcategories_cat_title'] = 'General';

$lang_install['bbconfig_board_disable_msg'] = 'The board is currently disabled...';
$lang_install['bbconfig_default_dateformat'] = 'D M d, Y g:i a';
$lang_install['bbconfig_locked_view_open'] = 'Locked: <strike>';
$lang_install['bbconfig_locked_view_close'] = '</strike>';
$lang_install['bbconfig_global_view_open'] = 'Global Announcement:';
$lang_install['bbconfig_global_view_close'] = '';
$lang_install['bbconfig_announce_view_open'] = 'Announcement:';
$lang_install['bbconfig_announce_view_close'] = '';
$lang_install['bbconfig_sticky_view_open'] = 'Sticky:';
$lang_install['bbconfig_sticky_view_close'] = '';
$lang_install['bbconfig_moved_view_open'] = 'Moved:';
$lang_install['bbconfig_moved_view_close'] = '';

$lang_install['bbextension_groups_Images'] = 'Images';
$lang_install['bbextension_groups_Archives'] = 'Archives';
$lang_install['bbextension_groups_Plain_Text'] = 'Plain Text';
$lang_install['bbextension_groups_Documents'] = 'Documents';
$lang_install['bbextension_groups_Real_Media'] = 'Real Media';
$lang_install['bbextension_groups_Streams'] = 'Streams';
$lang_install['bbextension_groups_Flash_Files'] = 'Flash Files';

$lang_install['bbforums_forum_name'] = 'Site';

$lang_install['bbgroups_group_name_Anonymous'] = 'Anonymous';
$lang_install['bbgroups_group_name_Moderators'] = 'Moderators';
$lang_install['bbgroups_group_description_Moderators'] = 'Moderators of this Forum';
$lang_install['bbgroups_group_name_Administrators'] = 'Administrators';
$lang_install['bbgroups_group_description_Administrators'] = 'Administrators of this Forum';
$lang_install['bbgroups_group_name_Users'] = 'Users';
$lang_install['bbgroups_group_description_Users'] = 'Default Usergroup';

$lang_install['bbposts_text_post_subject'] = 'Welcome to Nuke-Evolution!';
$lang_install['bbposts_text_post_text'] = 'Thanks for installing Nuke-Evolution.<br /><br />The Evo Team has put a lot of hard work into this release to make it the fastest, most functional and most secure version of PHP-Nuke ever. We encourage you to read through all of the included documentation so you fully understand the power within Evo.<br /><br />Inside the original archive you downloaded you will find several folders containing helpful information.<br /><br />The first is the "Install" folder which we hope you are already familiar with. This folder contains three documents which help you properly install and configure your new Evo site. If you haven\'t fully gone through these already please do it now!<br /><br />The second is the "Help" folder. Inside this folder you will find some very helpful documents that our team has put together to explain some of the features inside Evo. You will also find some documents that will help resolve a few errors you may run in to due to browser settings or improperly setup software.<br /><br />The third is the "Theme Edits" folder. If you would like to convert a PHP-Nuke theme to work with Evo you must follow the provided instructions within this folder.\r\n\r\nWe trust that Evo will be the best Nuke software you have ever run. Enjoy and be sure to stop by www.nuke-evolution.com for support, updates or just to say hi!<br /><br />[b:16f8943d60]- The Nuke-Evolution Team[/b:16f8943d60]';

$lang_install['bbquota_limits_Low'] = 'Low';
$lang_install['bbquota_limits_Medium'] = 'Medium';
$lang_install['bbquota_limits_High'] = 'High';

$lang_install['bbranks_rank_title_Site_Owner'] = 'Site Owner';
$lang_install['bbranks_rank_title_Site_Admin'] = 'Site Admin';

$lang_install['bbsmilies_Very_Happy'] = 'Very Happy';
$lang_install['bbsmilies_Smile'] = 'Smile';
$lang_install['bbsmilies_Sad'] = 'Sad';
$lang_install['bbsmilies_Surprised'] = 'Surprised';
$lang_install['bbsmilies_Shocked'] = 'Shocked';
$lang_install['bbsmilies_Confused'] = 'Confused';
$lang_install['bbsmilies_Cool'] = 'Cool';
$lang_install['bbsmilies_Laughing'] = 'Laughing';
$lang_install['bbsmilies_Mad'] = 'Mad';
$lang_install['bbsmilies_Razz'] = 'Razz';
$lang_install['bbsmilies_Embarassed'] = 'Embarassed';
$lang_install['bbsmilies_Crying_or_Very_sad'] = 'Crying or Very sad';
$lang_install['bbsmilies_Evil_or_Very_Mad'] = 'Evil or Very Mad';
$lang_install['bbsmilies_Twisted_Evil'] = 'Twisted Evil';
$lang_install['bbsmilies_Rolling_Eyes'] = 'Rolling Eyes';
$lang_install['bbsmilies_Wink'] = 'Wink';
$lang_install['bbsmilies_Exclamation'] = 'Exclamation';
$lang_install['bbsmilies_Question'] = 'Question';
$lang_install['bbsmilies_Idea'] = 'Idea';
$lang_install['bbsmilies_Arrow'] = 'Arrow';
$lang_install['bbsmilies_Neutral'] = 'Neutral';
$lang_install['bbsmilies_Mr_Green'] = 'Mr. Green';

$lang_install['bbstats_module_info_long_name_modul1'] = 'Statistics Overview Section';
$lang_install['bbstats_module_info_extra_info_modul1'] = 'This Module will print out a link Block with Links to the current Module at the Statistics Site.\nYou are able to define the number of columns displayed for this Module within the Administration Panel -&gt; Edit Module.';
$lang_install['bbstats_module_info_long_name_modul2'] = 'Top Posters';
$lang_install['bbstats_module_info_extra_info_modul2'] = 'This Module displays the Top Posters from your board.\nAnonymous Poster are not counted.';
$lang_install['bbstats_module_info_long_name_modul3'] = 'Administrative Statistics';
$lang_install['bbstats_module_info_extra_info_modul3'] = 'This Module displays some Admin Statistics about your Board.\nIt is nearly the same you are able to see within the first Administration Panel visit.';
$lang_install['bbstats_module_info_long_name_modul4'] = 'Most viewed topics';
$lang_install['bbstats_module_info_extra_info_modul4'] = 'This Module displays the most viewed topics at your board.';
$lang_install['bbstats_module_info_long_name_modul5'] = 'Top Posters this Month (Site History Mod)';
$lang_install['bbstats_module_info_extra_info_modul5'] = 'This Module does NOT require the Site History Mod,\nit will display the Top Posters on a Monthly basis.';
$lang_install['bbstats_module_info_long_name_modul6'] = 'New topics by month';
$lang_install['bbstats_module_info_extra_info_modul6'] = 'This Module will display the topics created at your Board in a monthly statistic.';
$lang_install['bbstats_module_info_long_name_modul7'] = 'Most Interesting Topics';
$lang_install['bbstats_module_info_extra_info_modul7'] = 'This module will show the most interesting topics.';
$lang_install['bbstats_module_info_long_name_modul8'] = 'Top Words';
$lang_install['bbstats_module_info_extra_info_modul8'] = 'This Module displays the most used words on your board.';
$lang_install['bbstats_module_info_long_name_modul9'] = 'Least Interesting Topics';
$lang_install['bbstats_module_info_extra_info_modul9'] = 'This module will show the least interesting topics.';
$lang_install['bbstats_module_info_long_name_modul10'] = 'Most Active Topicstarter';
$lang_install['bbstats_module_info_extra_info_modul10'] = 'This Module displays the most active topicstarter on your board.\nAnonymous Poster are not counted.';
$lang_install['bbstats_module_info_long_name_modul11'] = 'Top Smilies';
$lang_install['bbstats_module_info_extra_info_modul11'] = 'This Module displays the Top Smilies used at your board.\nThis Module uses an Smilie Index Table for caching the smilie data and to not\nrequire re-indexing of all posts.';
$lang_install['bbstats_module_info_long_name_modul12'] = 'New users by month';
$lang_install['bbstats_module_info_extra_info_modul12'] = 'This Module will display the users registered to your Board in a monthly statistic.';
$lang_install['bbstats_module_info_long_name_modul13'] = 'New posts by month';
$lang_install['bbstats_module_info_extra_info_modul13'] = 'This Module will display the posts created at your Board in a monthly statistic.';
$lang_install['bbstats_module_info_long_name_modul14'] = 'Top Posters this Week (Site History Mod)';
$lang_install['bbstats_module_info_extra_info_modul14'] = 'This Module does NOT require the Site History Mod,\nit will display the Top Posters on a Weekly basis.';
$lang_install['bbstats_module_info_long_name_modul15'] = 'Top Downloaded Attachments';
$lang_install['bbstats_module_info_extra_info_modul15'] = 'This Module will print out the most downloaded Files.\nThe Attachment Mod Version 2.3.x have to be installed in order to let this Module work.\nYou are able to exclude Images from the statistic too.';
$lang_install['bbstats_module_info_long_name_modul16'] = 'Most active Topics';
$lang_install['bbstats_module_info_extra_info_modul16'] = 'This Module displays the most active topics at your board.';

$lang_install['bbthemes_name_tr_color1_name'] = 'The lightest row color';
$lang_install['bbthemes_name_tr_color2_name'] = 'The medium row color';
$lang_install['bbthemes_name_tr_color3_name'] = 'The darkest row color';
$lang_install['bbthemes_name_tr_class1_name'] = '';
$lang_install['bbthemes_name_tr_class2_name'] = '';
$lang_install['bbthemes_name_tr_class3_name'] = '';
$lang_install['bbthemes_name_th_color1_name'] = 'Border round the whole page';
$lang_install['bbthemes_name_th_color2_name'] = 'Outer table border';
$lang_install['bbthemes_name_th_color3_name'] = 'Inner table border';
$lang_install['bbthemes_name_th_class1_name'] = 'Silver gradient picture';
$lang_install['bbthemes_name_th_class2_name'] = 'Blue gradient picture';
$lang_install['bbthemes_name_th_class3_name'] = 'Fade-out gradient on index';
$lang_install['bbthemes_name_td_color1_name'] = 'Background for quote boxes';
$lang_install['bbthemes_name_td_color2_name'] = 'All white areas';
$lang_install['bbthemes_name_td_color3_name'] = '';
$lang_install['bbthemes_name_td_class1_name'] = 'Background for topic posts';
$lang_install['bbthemes_name_td_class2_name'] = '2nd background for topic posts';
$lang_install['bbthemes_name_td_class3_name'] = '';
$lang_install['bbthemes_name_fontface1_name'] = 'Main fonts';
$lang_install['bbthemes_name_fontface2_name'] = 'Additional topic title font';
$lang_install['bbthemes_name_fontface3_name'] = 'Form fonts';
$lang_install['bbthemes_name_fontsize1_name'] = 'Smallest font size';
$lang_install['bbthemes_name_fontsize2_name'] = 'Medium font size';
$lang_install['bbthemes_name_fontsize3_name'] = 'Normal font size (post body etc)';
$lang_install['bbthemes_name_fontcolor1_name'] = 'Quote & copyright text';
$lang_install['bbthemes_name_fontcolor2_name'] = 'Code text color';
$lang_install['bbthemes_name_fontcolor3_name'] = 'Main table header text color';
$lang_install['bbthemes_name_span_class1_name'] = '';
$lang_install['bbthemes_name_span_class2_name'] = '';
$lang_install['bbthemes_name_span_class3_name'] = '';

$lang_install['bbtopics_topic_title'] = 'Welcome to EVO CMS!';

$lang_install['bbxdata_fields_field_name_icq'] = 'ICQ Number';
$lang_install['bbxdata_fields_field_name_aim'] = 'AIM Address';
$lang_install['bbxdata_fields_field_name_msn'] = 'MSN Messenger';
$lang_install['bbxdata_fields_field_name_yim'] = 'Yahoo Messenger';
$lang_install['bbxdata_fields_field_name_website'] = 'Website';
$lang_install['bbxdata_fields_field_name_location'] = 'Location';
$lang_install['bbxdata_fields_field_name_occupation'] = 'Occupation';
$lang_install['bbxdata_fields_field_name_interests'] = 'Interests';
$lang_install['bbxdata_fields_field_name_signature'] = 'Signature';

$lang_install['blocks_bkey_Main_Menu'] = 'Main Menu';
$lang_install['blocks_bkey_Administration'] = 'Administration';
$lang_install['blocks_bkey_Search'] = 'Search';
$lang_install['blocks_bkey_Survey'] = 'Survey';
$lang_install['blocks_bkey_Information'] = 'Information';
$lang_install['blocks_bkey_User_Info'] = 'User Info';
$lang_install['blocks_bkey_Nuke_Evolution'] = 'EVO CMS';
$lang_install['blocks_bkey_Hacker_Beware'] = 'Hacker Beware';
$lang_install['blocks_bkey_Top_10_Downloads'] = 'Top 10 Downloads';
$lang_install['blocks_bkey_Top_10_Links'] = 'Top 10 Links';
$lang_install['blocks_bkey_Forums'] = 'Forums';
$lang_install['blocks_bkey_Submissions'] = 'Submissions';
$lang_install['blocks_bkey_Link_to_us'] = 'Link to us';
$lang_install['blocks_bkey_Donations'] = 'Donations';

$lang_install['config_slogan'] = 'Your slogan here';
$lang_install['config_foot1'] = '<a href="modules.php?name=Spambot_Killer" target="_blank">Spambot Killer</a><br /><a href="modules.php?name=Site_Map" target="_blank"><strong>Site Map</strong></a><br />';
$lang_install['config_foot2'] = '<a href="rss.php?feed=news" target="_blank"><img border="0" src="images/powered/feed_20_news.png" width="94" height="15" alt="[News Feed]" title="News Feed" /></a> <a href="rss.php?feed=forums" target="_blank"><img border="0" src="images/powered/feed_20_forums.png" width="94" height="15" alt="[Forums Feed]" title="Forums Feed" /></a> <a href="rss.php?feed=downloads" target="_blank"><img border="0" src="images/powered/feed_20_down.png" width="94" height="15" alt="[Downloads Feed]" title="Downloads Feed" /></a> <a href="rss.php?feed=weblinks" target="_blank"><img border="0" src="images/powered/feed_20_links.png" width="94" height="15" alt="[Web Links Feed]" title="Web Links Feed" /></a>  <a href="http://htmlpurifier.org/"><img src="images/powered/html_purifier_powered.png" alt="Powered by HTML Purifier" border="0" /></a> <a href="http://tool.motoricerca.info/robots-checker.phtml?checkreferer=1" target="_blank"><img border="0" src="images/powered/valid-robots.png" width="80" height="15" alt="[Validate robots.txt]" title="Validate robots.txt" /></a><br />';
$lang_install['config_foot3'] = '';
$lang_install['config_anonymous'] = 'Anonymous';
$lang_install['config_backend_title'] = 'EVO CMS Powered Site';
$lang_install['config_notify_subject'] = 'NEWS for my site';
$lang_install['config_notify_message'] = 'Hey! You got a new submission for your site.';

$lang_install['cnbya_config_tos_text'] = 'This is your default TOS. You may edit this through the Evo-Administration - Settings paneel.';

$lang_install['donators_config_block_message'] = 'Find our site useful? Make a small donation to show your support.';
$lang_install['donators_config_gen_donation_name'] = 'Site Donation';
$lang_install['donators_config_gen_currency'] = 'USD';
$lang_install['donators_config_gen_date_format'] = 'm/d/Y';
$lang_install['donators_config_gen_thank_message'] = 'Thank you for your kind donation!<br /><br />Please come again!';
$lang_install['donators_config_gen_cancel_message'] = 'Sorry you could not donate!<br /><br />Please come again!';

$lang_install['downloads_categories_title'] = 'General';
$lang_install['downloads_categories_cdescription'] = 'General Category created during installation';

$lang_install['evo_userinfo_good_afternoon'] = 'Good Afternoon';
$lang_install['evo_userinfo_username'] = 'Username';
$lang_install['evo_userinfo_show_ip'] = 'Show IP';
$lang_install['evo_userinfo_avatar'] = 'Avatar';
$lang_install['evo_userinfo_personal_message'] = 'Personal Message';
$lang_install['evo_userinfo_rank'] = 'Rank';
$lang_install['evo_userinfo_mostever'] = 'Most Ever';
$lang_install['evo_userinfo_language'] = 'Language';
$lang_install['evo_userinfo_Break'] = 'Break';
$lang_install['evo_userinfo_pms'] = 'PMs';
$lang_install['evo_userinfo_themes'] = 'Themes';
$lang_install['evo_userinfo_login'] = 'Login/logout/register';
$lang_install['evo_userinfo_members'] = 'Members';
$lang_install['evo_userinfo_online'] = 'Online';
$lang_install['evo_userinfo_users'] = 'Users';
$lang_install['evo_userinfo_posts'] = 'Posts';

$lang_install['evo_userinfo_addons_good_afternoon_message'] = 'Good morning %name%:';
$lang_install['evo_userinfo_addons_personal_message_message'] = '<div align="center">Hello %name%, <br />Welcome to %site%.</div>';

$lang_install['evolution_censor_words'] = 'ass asshole arse bitch bullshit c0ck clit cock crap cum cunt fag faggot fuck fucker fucking fuk fuking motherfucker pussy shit tits twat';

$lang_install['links_categories_title'] = 'General';
$lang_install['links_categories_cdescription'] = 'General Category created during installation';


$lang_install['modules_meta_keywords'] = 'Nuke-Evolution, evo, pne, evolution, nuke, php-nuke, software, downloads, community, forums, bulletin, boards, cms, nuke-evo, phpnuke';

$lang_install['modules_title_Advertising'] = 'Advertising';
$lang_install['modules_title_Content'] = 'Content';
$lang_install['modules_title_Docs'] = 'Docs';
$lang_install['modules_title_Donations'] = 'Donations';
$lang_install['modules_title_Downloads'] = 'Downloads';
$lang_install['modules_title_FAQ'] = 'FAQ';
$lang_install['modules_title_Feedback'] = 'Feedback';
$lang_install['modules_title_Forums'] = 'Forums';
$lang_install['modules_title_Groups'] = 'Groups';
$lang_install['modules_title_News'] = 'News';
$lang_install['modules_title_NukeSentinel'] = 'NukeSentinel';
$lang_install['modules_title_Private_Messages'] = 'Private Messages';
$lang_install['modules_title_Profile'] = 'Profile';
$lang_install['modules_title_Recommend_Us'] = 'Recommend Us';
$lang_install['modules_title_Reviews'] = 'Reviews';
$lang_install['modules_title_Search'] = 'Search';
$lang_install['modules_title_Site_Map'] = 'Site Map';
$lang_install['modules_title_Spambot_Killer'] = 'Spambot Killer';
$lang_install['modules_title_Statistics'] = 'Statistics';
$lang_install['modules_title_Stories_Archive'] = 'Stories Archive';
$lang_install['modules_title_Submit_News'] = 'Submit News';
$lang_install['modules_title_Supporters'] = 'Supporters';
$lang_install['modules_title_Surveys'] = 'Surveys';
$lang_install['modules_title_Top'] = 'Top';
$lang_install['modules_title_Topics'] = 'Topics';
$lang_install['modules_title_Web_Links'] = 'Web Links';
$lang_install['modules_title_Your_Account'] = 'Your Account';

$lang_install['modules_cat_Home'] = 'Home';
$lang_install['modules_cat_Members'] = 'Members';
$lang_install['modules_cat_Community'] = 'Community';
$lang_install['modules_cat_Statistics'] = 'Statistics';
$lang_install['modules_cat_Files_Links'] = 'Files&nbsp;&amp;&nbsp;Links';
$lang_install['modules_cat_News'] = 'News';
$lang_install['modules_cat_Other'] = 'Other';


$lang_install['modules_links_title'] = 'Home';

$lang_install['poll_data_optionText_1'] = 'Ummmm, not bad';
$lang_install['poll_data_optionText_2'] = 'Cool';
$lang_install['poll_data_optionText_3'] = 'Terrific';
$lang_install['poll_data_optionText_4'] = 'The best one!';
$lang_install['poll_data_optionText_5'] = 'what the hell is this?';
$lang_install['poll_data_optionText_6'] = '';
$lang_install['poll_data_optionText_7'] = '';
$lang_install['poll_data_optionText_8'] = '';
$lang_install['poll_data_optionText_9'] = '';
$lang_install['poll_data_optionText_10'] = '';
$lang_install['poll_data_optionText_11'] = '';
$lang_install['poll_data_optionText_12'] = '';

$lang_install['poll_data_pollTitle'] = 'What do you think about this site?';
$lang_install['poll_data_planguage'] = 'english';

$lang_install['quotes_quote'] = 'Nos morituri te salutamus - CBHS';

$lang_install['reviews_categories_title'] = 'General';
$lang_install['reviews_categories_cdescription'] = 'General Category created during installation';

$lang_install['stories_title'] = 'Welcome To EVO CMS';
$lang_install['stories_hometext'] = 'Welcome to EVO CMS.<br /><br />You must now setup an admin account.  You can do this by <a href="admin.php">clicking here</a>.<br /><br /><br /><br /><strong>NOTE:</strong> You can remove this by going into the News Administration or by clicking the delete button below.';

$lang_install['stories_cat_Articles'] = 'Articles';

$lang_install['themes_custom_name'] = 'Chromo';

$lang_install['topics_text'] = 'EVO CMS';
$lang_install['topics_name'] = 'evolution';

$lang_install['users_name_Anonymous'] = 'Anonymous';
$lang_install['users_timezone_Anonymous'] = '1.00';
$lang_install['users_lang_Anonymous'] = 'english';
$lang_install['users_dateformat_Anonymous'] = 'D M d, Y g:i a';


?>