<?php
/*=======================================================================
 Nuke-Evolution   :   Enhanced Web Portal System
 ========================================================================

 Nuke-Evo Base          :   #$#BASE
 Nuke-Evo Version       :   #$#VER
 Nuke-Evo Build         :   #$#BUILD
 Nuke-Evo Patch         :   #$#PATCH
 Nuke-Evo Filename      :   #$#FILENAME
 Nuke-Evo Date          :   #$#DATE

 Copyright (c) 2010 by The Nuke Evolution Development Team
 ========================================================================

 LICENSE INFORMATIONS COULD BE FOUND IN COPYRIGHTS.PHP WHICH MUST BE
 DISTRIBUTED WITHIN THIS MODULEPACKAGE OR WITHIN FILES WHICH ARE
 USED FROM WITHIN THIS PACKAGE.
 IT IS "NOT" ALLOWED TO DISTRIBUTE THIS MODULE WITHOUT THE ORIGINAL
 COPYRIGHT-FILE.
 ALL INFORMATIONS ABOVE THIS SECTION ARE "NOT" ALLOWED TO BE REMOVED.
 THEY HAVE TO STAY AS THEY ARE.
 IT IS ALLOWED AND SHOULD BE DONE TO ADD ADDITIONAL INFORMATIONS IN
 THE SECTIONS BELOW IF YOU CHANGE OR MODIFY THIS FILE.

/*****[CHANGES]**********************************************************
-=[Base]=-
-=[Mod]=-
 ************************************************************************/

if(!defined('NUKE_EVO')) { die('It\'s not allowed to access this file directly'); }

$faq[] = array("--","Registrieren und Einloggen");
$faq[] = array("Warum kann ich mich nicht einloggen?", "Hast du dich registriert? Du musst dich erst registrieren, bevor du dich einloggen kannst. Wurdest du vom Board gebannt (in dem Fall erh&auml;lst du eine Nachricht)? Wenn dem so ist, solltest du den Webmaster oder den Forumsadministrator kontaktieren, um herauszufinden, warum. Falls du registriert und nicht gebannt bist und dich immer noch nicht einloggen kannst, dann &uuml;berpr&uuml;fe deinen Usernamen und das Passwort. Normalerweise liegt hier der Fehler, falls nicht, kontaktiere den Forumsadministrator, es k&ouml;nnten eine fehlerhafte Forumskonfiguration vorliegen.");
$faq[] = array("Warum muss ich mich &uuml;berhaut registrieren?", "Es kann auch sein, dass du das gar nicht musst, das ist die Entscheidung des Administrators. Auf jeden Fall erh&auml;lst du nach der Registrierung zus&auml;tzliche Funktionen, die G&auml;ste nicht haben, z.B. Avatare, Private Nachrichten, Eintritt in Usergruppen, usw. Es dauert nur wenige Augenblicke sich zu registrieren, du solltest es also tun.");
$faq[] = array("Warum logge ich mich automatisch aus?", "Solltest du die Funktion <i>Automatisch einloggen</i> beim Einloggen nicht aktiviert haben, bleibst du nur f&uuml;r eine gewisse Zeit eingeloggt. Dadurch wird der Mi&szlig;brauch deines Accounts verhindert. Um eingeloggt zu bleiben, w&auml;hle die entsprechende Option beim Einloggen. Dies ist nicht empfehlenswert, wenn du an einem fremden Rechner sitzt, z.B. in einer B&uuml;cherei oder Universit&auml;t, im Internetcaf&eacute; usw.");
$faq[] = array("Wie kann ich verhindern, dass man Name in der 'Wer ist online?'-Liste auftaucht?", "In deinem Profil findest du die Funktion <i>Onlinestatus verbergen</i>, und wenn du diese aktivierst, k&ouml;nnen dich nur noch Administratoren in der Liste sehen. Du z&auml;hlst dann als versteckter User.");
$faq[] = array("Ich habe mein Passwort verloren!", "Kein Problem! Du kannst ein neues Passwort beantragen. Klicke dazu auf der Loginseite auf <u>Ich habe mein Passwort vergessen</u>, folge den Anweisungen und du solltest dich bald wieder anmelden k&ouml;nnen.");
$faq[] = array("Ich habe mich registriert, kann mich aber nicht einloggen!", "&Uuml;berpr&uuml;fe erst, ob du den richtigen Usernamen und/oder Passwort angegeben hast. Falls sie stimmen, gibt es zwei M&ouml;glichkeiten, was passiert ist: Wenn die COPPA Bestimmungen aktiviert sind und du die Option <u>Ich bin unter 12 Jahre alt</u> beim Registrieren gew&auml;hlt hast, musst du den erhaltenen Anweisungen folgen. Falls dies nicht der Fall ist, braucht dein Account eine Aktivierung. Auf einigen Boards ist es der Fall, dass eine Registrierung immer erst aktiviert werden muss, bevor du dich einloggen kannst - entweder von dir selbst oder vom Administrator. Beim Registrieren wird dir gesagt, ob eine Aktivierung ben&ouml;tigt wird. Falls dir eine E-Mail zugesandt wurde, folge den enthaltenen Anweisungen, falls du diese E-Mail nicht erhalten hast, vergewissere dich, dass die E-Mail-Adresse korrekt war. Ein Grund f&uuml;r den Gebrauch der Account-Aktivierungen ist die Verhinderung eines Missbrauchs des Forums. Wenn du dir sicher bist, dass die angegebene E-Mail Adresse richtig ist, kontaktiere den Administrator.");
$faq[] = array("Ich habe mich vor einiger Zeit registriert, kann mich aber nicht mehr einloggen!", "Die Gr&uuml;nde daf&uuml;r sind meistens, dass du entweder einen falschen Usernamen oder ein falsches Psswort eingegeben hast (&uuml;berpr&uuml;fe die E-Mail, die du vom Board geschickt bekommen hast) oder der Administrator hat deinen Account gel&ouml;scht. Falls letzteres der Fall ist, hast du vielleicht mit dem Account noch nichts gepostet? Es ist durchaus &uuml;blich, dass Foren regelm&auml;&szlig;ig User l&ouml;schen, die nichts gepostet haben, um die Gr&ouml;&szlig;e der Datenbank zu verringern. Versuche dich erneut zu registrieren und tauche wieder ein in die Welt der Diskussionen.");
$faq[] = array("--","Userangaben und Einstellungen");
$faq[] = array("Wie &auml;ndere ich meine Einstellungen?", "Deine Einstellungen (sofern du registriert bist) werden in der Datenbank gespeichert. Klicke auf den <u>Profil</u>-Link, um sie zu &auml;ndern (wird normalerweise am oberen Bildschirmrand angezeigt, h&auml;ngt aber vom Style ab). Damit kannst du deine Einstellungen &auml;ndern");
$faq[] = array("Die Zeiten stimmen nicht!", "Die Zeiten stimmen h&ouml;chstwahrscheinlich schon, vermutlich hast du einfach die Zeitzone nicht richtig eingestellt. Falls dem so ist, solltest du die Einstellungen deines Profils &uuml;berpr&uuml;fen, um die Zeitzone, die f&uuml;r dich zutreffend ist, zu w&auml;hlen. Bitte beachte, dass du die Zeitzone nur wechseln kannst, wenn du ein registriertes Mitglied bist. Falls du also noch nicht registriert bist, w&auml;re das vielleicht ein guter Grund dazu.");
$faq[] = array("Ich habe die Zeitzone gewechselt und die Zeit ist immer noch falsch!", "Wenn du dir sicher bist, die richtige Zeitzone gew&auml;hlt zu haben und die Zeiten immer noch nicht stimmen, kann es daran liegen, dass das System auf Sommerzeit steht. Das Board ist nicht dazu geschaffen worden, zwischen Winter- und Sommerzeit zu wechseln, weswegen es im Sommer zu einer Stunde Differenz zwischen deiner gew&auml;hlten und der Boardzeit kommen kann.");
$faq[] = array("Meine Sprache ist nicht verf&uuml;gbar!", "Der wahrscheinlichste Grund daf&uuml;r ist, dass der Administrator die Sprache nicht installiert hat oder das Board wurde noch nicht in deine Sprache &uuml;bersetzt. Versuche, den Board-Administrator davon zu &uuml;berzeugen, dein Sprachfile zu installieren oder, fall es nicht existiert, kannst du auch gerne selber eine &Uuml;bersetzung schreiben. Weitere Informationen erh&auml;lst du auf der phpBB Group Website (Der Link ist am Ende jeder Seite)");
$faq[] = array("Wie kann ich ein Bild unter meinem Usernamen anzeigen?", "Es k&ouml;nenn sich zwei Bilder unter dem Usernamen befinden. Das erste geh&ouml;rt zu deinem Rang, z.B. Punkte oder Sterne, die anzeigen, wie viele Beitr&auml;ge du geschrieben hast oder welchen Status du im Forum hast. Darunter befindet sich meist ein gr&ouml;&szlig;eres Bild, Avatar genannt. Dies ist normalerweise ein Einzelst&uuml;ck und an den User gebunden. Es liegt am Administrator, ob er Avatare erlaubt und ob die User w&auml;hlen d&uuml;rfen, wie sie ihren Avatar zug&auml;nglich machen. Wenn du keine Avatare benutzen kannst, ist das eine Entscheidung des Administrators. Du solltest ihn nach dem Grund fragen (Er wird bestimmt einen guten haben).");
$faq[] = array("Wie kann ich meinen Rang &auml;ndern?", "Normalerweise kannst du nicht direkt den Wortlaut des Ranges &auml;ndern (R&auml;nge erscheinen unter deinem Usernamen in Themen und in deinem Profil, abh&auml;ngig davon, welchen Style du benutzt). Die meisten Boards benutzen R&auml;nge, um anzuzeigen, wie viele Beitr&auml;ge geschrieben wurden und bestimmte User, z.B. Moderatoren oder Administratoren, k&ouml;nnten einen speziellen Rang haben. Bitte bel&auml;stige das Forum nicht mit unn&ouml;tigen Beitr&auml;gen, nur um deinen Rang zu erh&ouml;hen, sonst wirst du auf einen Moderator oder Administrator treffen, der deinen Rang einfach wieder senkt.");
$faq[] = array("Wenn ich auf den E-Mail-Link eines Users klicke, werde ich dazu aufgefordert, mich einzuloggen!", "Nur registrierte User k&ouml;nnen &uuml;ber das Forum E-Mails versenden (falls der Administrator diese Funktion zul&auml;sst). Damit sollen obsz&ouml;ne Mails von unbekannten Usern unterbunden werden.");
$faq[] = array("--","Beitr&auml;ge schreiben");
$faq[] = array("Wie schreibe ich ein Thema in ein Forum?", "Ganz einfach, klicke einfach auf den entsprechenden Button auf der Forums- oder Beitragsseite. Es kann sein, dass du dich erst registrieren musst, bevor du eine Nachricht schreiben kannst - deine verf&uuml;gbaren Aktionen werden am Ende der Seite aufgelistet (die <i>Du kannst neue Themen erstellen, Du kannst an Umfragen teilnehmen, usw.</i>-Liste)");
$faq[] = array("Wie editiere oder l&ouml;sche ich einen Beitrag?", "Sofern du nicht der Boardadministrator oder der Forumsmoderator bist, kannst du nur deine eigenen Beitr&auml;ge l&ouml;schen oder editieren. Du kannst einen Beitrag editieren (eventuell nur f&uuml;r eine gewisse Zeit) indem du auf den <i>Editieren</i>-Button des jeweiligen Beitrages klickst. Sollte jemand bereits auf den Beitrag geantwortet haben, wirst du einen kleinen Text unterhalb des Beitrags lesen k&ouml;nnen, der anzeigt, wie oft der Text bearbeitet wurde. Er wird nur erscheinen, wenn jemand geantwortet hat, ferner wird er nicht erscheinen, falls ein Moderator oder Administrator den Beitrag editiert hat (Sie sollten eine Nachricht hinterlassen, warum sie den Beitrag editierten). Beachte, dass normale User keine Beitr&auml;ge l&ouml;schen k&ouml;nnen, wenn schon jemand auf sie geantwortet hat.");
$faq[] = array("Wie kann ich eine Signatur anh&auml;ngen?", "Um eine Signatur an einen Beitrag anzuh&auml;ngen, musst du erst eine im Profil erstellen. Wenn du eine erstellt hast, aktiviere die <i>Signatur anh&auml;ngen</i>-Funktion w&auml;hrend der Beitragserstellung. Du kannst auch eine Standardsignatur an alle Beitr&auml;ge anh&auml;ngen, indem du im Profil die entsprechende Option anw&auml;hlst (du kannst das Anf&uuml;gen einer Signatur immer noch verhindern, indem du die Signaturoption beim Beitragssschreiben abschaltest)");
$faq[] = array("Wie erstelle ich eine Umfrage?", "Eine Umfrage zu erstellen ist recht einfach: Wenn du ein neues Thema erstellst, (oder den ersten Beitrag eines Themas editierst, sofern du die Erlaubnis dazu hast) solltest du die <i>Umfrage hinzuf&uuml;gen</i>-Option unterhalb der Textbox sehen (falls du sie nicht sehen kannst, hast du m&ouml;glicherweise nicht die erforderlichen Rechte). Du solltest einen Titel f&uuml;r deine Umfrage angeben und mindestens eine Antwortm&ouml;glichkeit (um eine Antwort anzugeben, klicke auf die <i>Antwort hinzuf&uuml;gen</i>-Schaltfl&auml;che. Du kannst auch ein Zeitlimit f&uuml;r die Umfrage setzen, 0 ist eine unbegrenzt dauernde Umfrage. Es gibt eine automatische Grenze bei der Anzahl an Antwortoptionen, diese legt der Administrator fest.");
$faq[] = array("Wie editiere oder l&ouml;sche ich eine Umfrage?", "Genau wie mit den Beitr&auml;gen, k&ouml;nnen Umfrage nur vom Verfasser, Forumsmoderator oder Administrator editiert oder gel&ouml;scht werden. Um eine Umfrage zu editieren, editiere den ersten Beitrag im Thema (die Umfrage ist immer damit verbunden). Wenn noch niemand bei der Umfrage mitgestimmt hat, k&ouml;nnen User die Umfrage editieren oder l&ouml;schen , falls jedoch schon jemand mitgestimmt hat, k&ouml;nnen sie nur Moderatoren oder Administratoren l&ouml;schen oder editieren. Damit soll verhindert werden, dass Personen ihre Umfragen beeinflussen, indem sie die Antworten ver&auml;ndern.");
$faq[] = array("Warum kann ich ein Forum nicht betreten?", "Manche Foren k&ouml;nnen nur von bestimmten Usern oder Gruppen betreten werden. Um dort hineinzugelangen, Beitr&auml;ge zu lesen oder zu schreiben usw., k&ouml;nntest du eine spezielle Erlaubnis brauchen. Nur der Forumsmoderator und der Boardadministrator k&ouml;nnen dir die Zugangsrechte daf&uuml;r geben, du solltest sie um Zugang bitten, sofern du einen berechtigten Grund daf&uuml;r hast.");
$faq[] = array("Warum kann ich bei Abstimmungen nicht mitmachen?", "Nur registrierte User k&ouml;nen an Umfragen teilnehmen. Dadurch wird eine Beeinflussung des Ergebnisses verhindert. Falls du dich registriert hast und immer noch nicht mitstimmen kannst, hast du vermutlich nicht die erforderlichen Rechte dazu.");
$faq[] = array("--","Was man in und mit Beitr&auml;gen tun kann");
$faq[] = array("Was ist BBCode?", "BBCode ist eine spezielle Abart von HTML. Ob du BBCode benutzen kannst, wird vom Administrator festgelegt. Du kannst es auch in einzelnen Beitr&auml;gen deaktivieren. BBCode selber ist HTML sehr &auml;hnlich, die Tags sind von den Klammern [ und ] umschlossen und bietet dir gro&szlig;e Kontrolle dar&uuml;ber, was und wie etwas angezeigt wird. F&uuml;r weitere Informationen &uuml;ber den BBCode solltest du dir die Anleitung anschauen, die du von der Beitrag schreiben-Seite aus erreichen kannst.");
$faq[] = array("Darf ich HTML benutzen?", "Das h&auml;ngt davon ab, ob es vom Administrator erlaubt wurde. Falls du es nicht darfst, wirst du nachher nur ein Klammer-Wirrwarr wieder finden. Dies ist eine <i>Sicherung</i>, um Leute davon abzuhalten, das Forum mit unn&ouml;tigen Tags zu &uuml;berschwemmen, die das Layout zerst&ouml;ren oder andere St&ouml;rungen hervorrufen k&ouml;nnten. Falls HTML aktiviert wurde, kannst du es immer noch manuell f&uuml;r jeden Beitrag deaktivieren, indem du beim Schreiben die entsprechende Option aktivierst.");
$faq[] = array("Was sind Smilies?", "Smilies sind kleine Bilder, die benutzt werden k&ouml;nnen, um Gef&uuml;hle auszudr&uuml;cken. Es werden nur kurze Codes ben&ouml;tigt, z.B. zeigt :) Freude und :( Traurigkeit an. Die komplette Liste der Smilies kann auf der Beitrag schreiben-Seite gesehen werden. &Uuml;bertreibe es nicht mit Smilies, es kann schnell passieren, dass ein Beitrag dadurch v&ouml;llig un&uuml;bersichtlich wird. Ein Moderator k&ouml;nnte sich entschlie&szlig;en, den Beitrag zu bearbeiten oder sogar komplett zu l&ouml;schen.");
$faq[] = array("Darf ich Bilder einf&uuml;gen?", "Bilder k&ouml;nnen in der Tat im Beitrag angezeigt werden. Auf jeden Fall gibt es noch keine M&ouml;glichkeit, Bilder direkt auf das Board hochzuladen.  Deshalb musst du zu einem bestehehden Bild verlinken, welches sich auf einem f&uuml;r die &Ouml;ffentlichkeit zug&auml;nglichen Server befindet. Z.B. http://www.meineseite.de/meinbild.gif. Du kannst weder zu Bildern linken, die sich auf deiner Festplatte befinden (au&szlig;er es handelt sich um einen &ouml;ffentlich verf&uuml;gbaren Server) noch zu Bildern, die einen speziellen Zugang brauchen, um sie anzuzeigen (z.B. E-Mail-Konten, Passwort-gesch&uuml;tzte Seiten usw). Um das Bild anzuzeigen, benutze entweder den BB-Code [img] oder nutze HMTL (sofern erlaubt).");
$faq[] = array("Was sind Ank&uuml;ndigungen?", "Ank&uuml;ndigungen beinhalten meistens wichtige Informationen und du solltest sie so fr&uuml;h wie m&ouml;glich lesen. Ank&uuml;ndigungen erscheinen immer am Anfang des jeweiligen Forums. Ob du eine Ank&uuml;ndigung machen kannst oder nicht h&auml;ngt davon ab, was f&uuml;r Befugnisse dazu eingerichtet wurden. Diese legt der Board-Administrator fest.");
$faq[] = array("Was sind Wichtige Themen?", "Wichtige Themen erscheinen unterhalb der Ank&uuml;ndigungen in der Forumsansicht. Sie enthalten auch meistens wichtige Informationen, die du gelesen haben solltest. Genau wie mit den Ank&uuml;ndigungen entscheidet auch bei den Wichtigen Themen der Administrator, wer sie erstellen darf und wer nicht.");
$faq[] = array("Was sind geschlossene Themen?", "Themen werden entweder vom Forumsmoderator oder dem Board-Administrator geschlossen. Man kann auf geschlossene Beitr&auml;ge nicht antworten und falls eine Umfrage angef&uuml;gt wurde, wird diese damit auch beendet. Es gibt verschiedene Gr&uuml;nde, warum ein Thema geschlossen wird.");
$faq[] = array("--","Userebenen und Gruppen");
$faq[] = array("Was sind Administratoren?", "Administratoren haben die h&ouml;chste Kontrollebene im gesamten Forum. Sie haben das Recht, jede Forumsaktion zu unterbinden und spezielle Aktionen durchzuf&uuml;hren, wie die Vergabe von Befugnissen, das Bannen von Usern, Usergruppen erstellen, Moderatoren ernennen usw. Sie haben au&szlig;erdem in jedem Forum die vollen Moderatorenrechte.");
$faq[] = array("Was sind Moderatoren?", "Moderatoren sind Personen (oder Gruppen) die auf das t&auml;gliche Geschehen in dem jeweiligen Forum achten. Sie haben die M&ouml;glichkeit, Beitr&auml;ge zu editieren und zu l&ouml;schen, Themen zu schlie&szlig;en, &ouml;ffnen, verschieben oder l&ouml;schen. Moderatoren haben die Aufgabe, die Leute davon abzuhalten, unpassende Themen in einen Beitrag zu schreiben oder sonstigen Bl&ouml;dsinn in das Forum zu setzen.");
$faq[] = array("Was sind Usergruppen?", "In Usergruppen werden einige User vom Administrator zusammengefasst. Jeder User kann zu mehreren Gruppen geh&ouml;ren und jeder Gruppe k&ouml;nnen spezielle Zugangsrechte erteilt werden. So ist es f&uuml;r den Administrator einfacher, mehrere User zu Moderatoren eines bestimmten Forums zu erkl&auml;ren, ihnen Rechte f&uuml;r ein privates Forum zu geben und so weiter.");
$faq[] = array("Wie kann ich einer Usergruppe beitreten?", "Um einer Usergruppe beizutreten, klicke auf den Usergruppen-Link im Men&uuml;, du erh&auml;lst dann einen &Uuml;berblick &uuml;ber alle Usergruppen. Nicht alle Gruppen haben <i>offenen Zugang</i>, manche sind geschlossen und andere k&ouml;nnten versteckt sein. Falls die Gruppe Mitglieder zul&auml;sst, kannst du um Einlass in die Gruppe bitten, indem du auf den Beitreten-Button klickst. Der Gruppenmoderaotr muss noch seine Zustimmung geben, eventuell gibt es R&uuml;ckfragen, warum du der Gruppe beitreten m&ouml;chtest. Bitte nerve die Gruppenmoderatoren nicht, nur weil sie dich nicht in die Gruppe aufnehmen wollen, sie werden ihre Gr&uuml;nde haben.");
$faq[] = array("Wie werde ich ein Gruppenmoderator?", "Usergruppen werden vom Board-Administrator erstellt, er bestimmt ebenfalls den Moderator. Falls du daran interessiert bist, eine Usergruppe zu erstellen, solltest du zuerst den Administrator kontaktieren, zum Beispiel mit einer Privaten Nachricht.");
$faq[] = array("--","Druckfreundliche Themenansicht");
$faq[] = array("F&uuml;r was ist der Button :| |:? - Entfernen des Seitenumbruchs vom Board", "Durch das Anklicken dieses Buttons kann der vom Board fixierte Seitenumbruch des aktuellen Themas entfernt werden.
 Somit wird der Seitenumbruch vom Webbrowser f&uuml;r das Ausdrucken &uuml;bernommen aufgrund der aktuellen Zeilenumbr&uuml;che und nicht aufgrund der im Forum eingestellten Anzahl von Nachrichten pro Seite.");
$faq[] = array("F&uuml;r was sind die Felder am Anfang der druckbaren Ansicht? - Bereich der Auswahl", "Es gibt 2 Felder am Anfang der Seite und einen Button <strong>zeigen</strong>.
 Mit diesen Feldern kann ein Bereich der Nachrichten ausgew&auml;hlt werden.
 Beachte, dass jede Nachricht in der druckbaren Ansicht eine Nummer hat.
 Verwende diese Nummern in den 2 Feldern um die erste und die letzte Nachricht, die Du gedruckt haben willst, auszuw&auml;hlen und klicke dann auf den Button <strong>zeigen</strong> um die Nachrichten neu anzuordnen.
 Eine andere Variante um den Bereich festzulegen ist, wenn Du eine negative Zahl in das zweite Feld eingibst.
 Das bedeutet Du willst -n Nachrichten ausdrucken. Als Beispiel: Gib in das erste Feld 4 und in das zweite Feld 7 ein, dann werden die Nachtrichten 4, 5, 6, 7 ausgedruckt.
 Wenn Du in das erste Feld 4 und in das zweite Feld -7 eingibst, werden die Nachrichten 4, 5, 6, 7, 8, 9, 10 angezeigt, nachdem Du den Button <strong>zeigen</strong> angeklickt hast.");
$faq[] = array("Wie kann ich nur eine Nachricht drucken? - Erweiterte Auswahl des Bereichs", "Als erstes gehst Du auf die druckbare Ansicht indem Du den Button Drucken in der Themenansicht anklickst.
 Suche Deine Nachricht, die Du drucken willst und notiere Dir die Nummer auf der linken Seite der Nachricht.
 Tippe diese Nummer in das erste Feld links am Anfnag der druckbaren Ansicht.
 In das zweite Feld gib -1 ein und klicke den Button <strong>zeigen</strong>.
 Dies gibt der Datenbank weiter, nur eine Nachricht auszugeben beginnend mit der eingegeben Nummer.
 Eine andere M&ouml;glichkeit ist, wenn Du einfach in beide Felder die gleiche Nummer eingbist.
 Sagen wir, Du willst die Nachricht mit der Nummer 16 drucken.
 Gib in die Felder am Anfang folgendes ein: 16 und -1 und klicke den Button <strong>zeigen</strong>.
 Anstatt 16 und -1 kannst Du auch einfach 16 und 16 eingeben. Das Ergebnis ist das selbe.
 Diese Beispiel funktioniert nat&uuml;rlich nur, wenn es mindestens 16 Nachrichten in dem aktuellen Thema gibt.");
$faq[] = array("Weitere Fragen?", "Detaillierte Dokumentation und das Support Forum findest Du <a href=\"http://wiking.sourceforge.net/phpBB2/wakka.php?wakka=PrinterFriendlyTopicView\">hier</a>");
$faq[] = array("--","Private Nachrichten");
$faq[] = array("Ich kann keine Privaten Nachrichten versenden!", "Es gibt drei m&ouml;gliche Gr&uuml;nde daf&uuml;r: Du bist nicht registriert bzw. eingeloggt, der Board-Administrator hat das Private Nachrichten-System f&uuml;r das gesamte Board abgeschaltet oder der Administrator hat dir das Schreiben von PMs untersagt. Falls das letzte zutreffen sollte, solltest du ihn fragen, warum.");
$faq[] = array("Ich erhalte dauernd ungewollte PMs!", "Es wird bald ein Ignorieren-System f&uuml;r das Private Nachrichten-System geben. Im Moment musst du, falls du ununterbrochen unerw&uuml;nschte Nachrichten von einer Person erh&auml;lst, den Administrator informieren. Er kann das Versenden von PMs durch den jeweiligen User unterbinden.");
$faq[] = array("Ich habe eine Spam- oder perverse E-Mail von jemandem auf diesem Board erhalten!", "Das E-Mail-System dieses Boards enth&auml;lt Sicherheitsvorkehrungen, um solche Aktionen eines Users zu verhindern. Du solltest dem Board-Administrator eine Kopie der erhaltenen E-Mail senden, wichtig dabei ist, dass die Kopfzeilen angef&uuml;gt bleiben (die Details &uuml;ber den User, der die E-Mail schickte). Erst dann kann er handeln.");
//
// DIE DREI UNTEN STEHENDEN FRAGEN DER FAQ SOLLEN UNÜBERSETZT BLEIBEN, DA ES SICH UM INTERNATIONALES RECHT HANDELT - LASST DIE DREI EINTRÄGE BITTE ENGLISCH!
//
$faq[] = array("--","phpBB 2 Issues (Informationen zu phpBB 2)");
$faq[] = array("Wer hat dieses Forum entwickelt?", "Diese Software (in ihrer unver&auml;nderten Form) ist produziert, herausgegeben und unterliegt dem Copyright  <a href=\"http://www.phpbb.com/\" target=\"_blank\">phpBB Group</a>. Es wird ver&ouml;ffentlicht unter GNU General Public Licence und darf frei weitergegeben werden, siehe Link f&uuml;r n&auml;here Informationen.");
$faq[] = array("Warum ist die Funktion X nicht verf&uuml;gbar?", "Diese Software wurde von der phpBB Group entwickelt und lizenziert. Solltest Du eine Funktion vermissen, besuche bitte die phpbb.com Webseite und schau dort zu diesem Thema. Bitte schreibe keine Funktionsw&uuml;nsche in das Board auf phpbb.com, die Gruppe nutzt sourceforge zur Planung neuer Funktionen. Bitte lies die Foren und schau nach wie, wenn &uuml;berhaupt, wir eventuell schon &uuml;ber die Funktion denken und folge der dort beschriebenen Prozedur.");
$faq[] = array("Wen kontaktiere ich im Falle des Mi&szlig;brauchs und/oder rechtlichen Angelegenheiten?", "Du solltest den Administrator dieses Boards kontaktieren. Wenn Du nicht herausfinden kannst wer das ist, frage zun&auml;chst einen der Moderatoren des Boards, wer zu kontaktieren ist. Wenn Du immer noch keine Antwort erh&auml;ltst, kontaktiere den Besitzer der Domain (&uuml;ber whois Suche) oder, wenn das Board auf einem freien Service l&auml;uft (z.B. yahoo, free.fr, f2s.com, etc.), die Betreiber oder die Mi&szlig;brauchsabteilung dieses Services. Bitte beachte, da&szlig; die phpBB Group keinerlei Kontrolle dar&uuml;ber hat wie, wo oder von wem das Board eingesetzt wird und daher daf&uuml;r nicht haftbar gemacht werden kann.");
//
// This ends the FAQ entries
//

?>