<?php
/*=======================================================================
 Nuke-Evolution   :   Enhanced Web Portal System
 ========================================================================

 Nuke-Evo Base          :   #$#BASE
 Nuke-Evo Version       :   #$#VER
 Nuke-Evo Build         :   #$#BUILD
 Nuke-Evo Patch         :   #$#PATCH
 Nuke-Evo Filename      :   #$#FILENAME
 Nuke-Evo Date          :   #$#DATE

 Copyright (c) 2010 by The Nuke Evolution Development Team
 ========================================================================

 LICENSE INFORMATIONS COULD BE FOUND IN COPYRIGHTS.PHP WHICH MUST BE
 DISTRIBUTED WITHIN THIS MODULEPACKAGE OR WITHIN FILES WHICH ARE
 USED FROM WITHIN THIS PACKAGE.
 IT IS "NOT" ALLOWED TO DISTRIBUTE THIS MODULE WITHOUT THE ORIGINAL
 COPYRIGHT-FILE.
 ALL INFORMATIONS ABOVE THIS SECTION ARE "NOT" ALLOWED TO BE REMOVED.
 THEY HAVE TO STAY AS THEY ARE.
 IT IS ALLOWED AND SHOULD BE DONE TO ADD ADDITIONAL INFORMATIONS IN
 THE SECTIONS BELOW IF YOU CHANGE OR MODIFY THIS FILE.

/*****[CHANGES]**********************************************************
-=[Base]=-
-=[Mod]=-
 ************************************************************************/

if (!defined('MODULE_FILE')) {
    die ("You can't access this file directly...");
}

$module_name = basename(dirname(__FILE__));

// NON MODIFICARE IL CODICE SOTTOSTANTE
// DON'T TOUCH THE CODE BELOW
//--------------------------------------------------------------------------------------

global $db, $currentlang, $admin, $admin_file;

$result = $db->sql_query("SELECT * FROM "._JMAP_TABLE);
while ($row = $db->sql_fetchrow($result)) {
    $conf[$row['name']] = $row['value'];
}
$db->sql_freeresult($result);

$xml   = $conf['xml'];
$ndown = $conf['ndown'];
$nnews = $conf['nnews'];
$nrev  = $conf['nrev'];
$ntopics = $conf['ntopics'];
$nuser = $conf['nuser'];


if (@file_exists(NUKE_MODULES_DIR.$module_name.'/language/lang-'.$currentlang.'.php')) {
  include_once(NUKE_MODULES_DIR.$module_name.'/language/lang-'.$currentlang.'.php');
} else {
  include_once(NUKE_MODULES_DIR.$module_name.'/language/lang-english.php');
}

$pagetitle = $lang_new[$module_name]['MODULE_NAME'];

//---------------------- XML BEGIN -----------------
if($xml) {
  //OPEN FILE
  $var = @fopen(NUKE_BASE_DIR."sitemap.xml","w+");
  // HEADER
  @fwrite($var, "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>
<!--Google Site Map File Generated by Site_Map http://www.techg3n.net -->
<urlset xmlns=\"http://www.google.com/schemas/sitemap/0.84\">\n");
} else {
    //DELETE CONTENT
    $var = @fopen(NUKE_BASE_DIR."sitemap.xml","w+");
    @fclose($var);
}
//---------------------- XML END -----------------

include_once(NUKE_BASE_DIR.'header.php');
//$text = $lang_new[$module_name]['NJMAP'].EVO_SERVER_SITENAME;
$text = "<table align=\"center\" border=\"0\">";
$text .= "<tr><td align=\"left\"><strong>".$lang_new[$module_name]['Key']."</strong><br /><br />";
$text .= "<img src=\"". evo_image('deny.gif', $module_name) ."\" alt=\"\" /> ".$lang_new[$module_name]['Key1']."<br />";
$text .= "<img src=\"". evo_image('cat1.gif', $module_name) ."\" alt=\"\" /> ".$lang_new[$module_name]['Key2']."<br />";
$text .= "<img src=\"". evo_image('cat3.gif', $module_name) ."\" alt=\"\" /> ".$lang_new[$module_name]['Key3']."<br />";
$text .= "<img src=\"". evo_image('cat2.gif', $module_name) ."\" alt=\"\" /> ".$lang_new[$module_name]['Key4']."<br />";
$text .= "<img src=\"". evo_image('catt.gif', $module_name) ."\" alt=\"\" /> ".$lang_new[$module_name]['Key5']."<br />";
$text .= "<img src=\"". evo_image('cath.gif', $module_name) ."\" alt=\"\" /> ".$lang_new[$module_name]['Key6']."<br /><br />";
$text .= $lang_new[$module_name]['Key0']."<br />";
$text .= "</td></tr></table>";
title($text, $module_name, 'site_map-logo.png');
get_blocklang('Modules');
OpenTable();
echo "<table align=\"center\" border=\"0\">";
echo "<tr><td><img src=\"". evo_image('cath.gif', $module_name) ."\" alt=\"cath\" /></td><td><a href=\"".EVO_SERVER_URL."\">".$lang_new[$module_name]['Key6']."</a></td></tr>\n";
$result2 = $db->sql_query("SELECT `title`, `custom_title`, `view`, `groups` FROM `" . _MODULES_TABLE . "` WHERE `active`=1 ORDER BY `custom_title`");
while ($row2 = $db->sql_fetchrow($result2)) {
    $custom_module_name = $row2['custom_title'];
    $link = $row2['title'];
    $permission = $row2['view'];
    $groups = $row2['groups'];
    $show = TRUE;
    $langname = FALSE;
    $original_custom = $row2['custom_title'];
    $is_link = FALSE;
    if(substr($link,0,3) == '~l~') {
        $link = substr($link,3);
        $is_link = TRUE;
    }
    if (isset($lang_block['MODULES_'.$link]) && (!empty($lang_block['MODULES_'.$link]))) {
        $custom_module_name = $lang_block['MODULES_'.$link];
        $langname = TRUE;
    } else if (isset($lang_block['MODULES_'.$custom_module_name]) && (!empty($lang_block['MODULES_'.$custom_module_name]))) {
        $custom_module_name = $lang_block['MODULES_'.$custom_module_name];
        $langname = TRUE;
    }
    echo "<tr><td>";
    if ($permission < 3) {
        echo "<img src=\"".evo_image('cat1.gif', $module_name)."\" alt=\"cat1\" />";
    } else if ($permission == 4 && is_admin()) {
        echo "<img src=\"". evo_image('cat1.gif', $module_name)."\" alt=\"cat1\" />";
    } else if ($permission == 6 && !empty($groups) && is_array($groups)) {
        $ingroup = false;
        global $userinfo;
        foreach ($groups as $group) {
            if (isset($userinfo['groups'][$group])) {
                $ingroup = true;
            }
        }
        if (!$ingroup) {
            echo "<img src=\"".evo_image('cat1.gif', $module_name)."\" alt=\"cat1\" />";
        } else {
            echo "<img src=\"". evo_image('deny.gif', $module_name)."\" alt=\"deny\" />";
            $show = false;
        }
    } else {
        echo "<img src=\"". evo_image('deny.gif', $module_name)."\" alt=\"deny\" />";
        $show = false;
    }
    echo "</td>\n";
    if($is_link) {
        $target = (strstr($original_custom, 'HTTP') ? 'target="_blank"' : '');
        echo "<td><a href=\"".htmlentities($original_custom)."\" ".$target.">".($langname ? $custom_module_name : $link)."</a></td></tr>\n";
    } else {
        echo "<td><a href=\"modules.php?name=$link\">$custom_module_name</a></td></tr>\n";
    }

  switch($link) {
    case 'Downloads':
      $result3 = $db->sql_query("SELECT `cid`, `title` FROM `" . _DOWNLOADS_CATEGORIES_TABLE . "` WHERE `catactive`=1 AND `parentid`=0 ORDER BY `title`");
      while ($row3 = $db->sql_fetchrow($result3)) {
        $down_title = $row3['title'];
        $cid1 = $row3['cid'];
        echo "<tr><td>&nbsp;</td><td><img src=\"".evo_image('cat3.gif', $module_name)."\" alt=\"cat3\" />&nbsp;<a href=\"modules.php?name=Downloads&amp;cid=$cid1\">$down_title</a></td></tr>";
        if($xml) {
            //XML-Output
            @fwrite($var, "  <url><loc>".EVO_SERVER_URL."/modules.php?name=Downloads&amp;cid=$cid1</loc></url>\n");
        }
        $result4 = $db->sql_query("SELECT `cid`, `title` FROM `" . _DOWNLOADS_CATEGORIES_TABLE . "` WHERE `catactive`=1 AND `parentid`=$cid1 ORDER BY `title`");
        while ($row4 = $db->sql_fetchrow($result4)) {
          $down_title2 = $row4['title'];
          $cid2 = $row4['cid'];
          echo "<tr><td>&nbsp;</td><td>&nbsp;&nbsp;&nbsp;&nbsp;<img src=\"".evo_image('cat2.gif', $module_name)."\" alt=\"cat2\" />&nbsp;<a href=\"modules.php?name=Downloads&amp;cid=$cid2\">$down_title2</a></td></tr>";
          if($xml) {
               //XML-Output
               @fwrite($var, "  <url><loc>".EVO_SERVER_URL."/modules.php?name=Downloads&amp;cid=$cid2</loc></url>\n");
          }
          $result4b = $db->sql_query("SELECT `cid`, `did`, `title` FROM `" . _DOWNLOADS_DOWNLOADS_TABLE . "` WHERE `download_active`=1 AND `cid`=$cid2 ORDER BY `hits` LIMIT 0,".$ndown);
          while ($row4b = $db->sql_fetchrow($result4b)) {
              $down_title3=$row4b['title'];
              $cid3 = $row4b['lid'];
              echo"<tr><td>&nbsp;</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src=\"".evo_image('catt.gif', $module_name)."\" alt=\"cat\" />&nbsp;<a href=\"modules.php?name=Downloads&amp;op=getit&amp;lid=$cid3\">$down_title3</a></td></tr>";
          }
          $db->sql_freeresult($result4b);
        }
        $db->sql_freeresult($result4);
      }
      $db->sql_freeresult($result3);
    break;

    case 'Forums':
      $result5 = $db->sql_query("SELECT `cat_id`, `cat_title` FROM `" . CATEGORIES_TABLE . "` ORDER BY `cat_order`");
      while ($row5 = $db->sql_fetchrow($result5)) {
        $catftitle = $row5['cat_title'];
        $cat_id = $row5['cat_id'];

        //Check to make sure its not a blank category
        $number_of_forums = $db->sql_numrows($db->sql_query("SELECT * FROM `" . FORUMS_TABLE . "` WHERE `cat_id`=$cat_id AND `auth_view`<2 AND `auth_read`<2 ORDER BY `forum_order`"));
        if ($number_of_forums <= 0) continue;

        echo "<tr><td>&nbsp;</td><td><img src=\"".evo_image('cat3.gif', $module_name)."\" alt=\"cat3\" /><a href=\"modules.php?name=Forums&amp;file=index&amp;c=$cat_id\">$catftitle</a></td></tr>";
        if($xml) {
             //XML-Output
             @fwrite($var, "  <url><loc>".EVO_SERVER_URL."/modules.php?name=Forums&amp;file=index&amp;c=$cat_id</loc><changefreq>daily</changefreq></url>\n");
        }
        $result6 = $db->sql_query("SELECT `forum_name`, `forum_id`, `auth_view`, `auth_read` FROM `" . FORUMS_TABLE . "` WHERE `cat_id`=$cat_id AND `auth_view`<2 AND `auth_read`<2 ORDER BY `forum_order`");
        while ($row6 = $db->sql_fetchrow($result6)) {
          $forum_name = $row6['forum_name'];
          $fid = $row6['forum_id'];
          $auth_view = $row6['auth_view'];
          $auth_read = $row6['auth_read'];
          echo"<tr><td>&nbsp;</td><td>";
          if ($auth_view && !is_user()) {
            echo "&nbsp;&nbsp;&nbsp;&nbsp;<img src=\"".evo_image('deny.gif', $module_name)."\" alt=\"deny\" />";
            echo "$forum_name</td></tr>";
          } else {
            echo "&nbsp;&nbsp;&nbsp;&nbsp;<img src=\"".evo_image('cat2.gif', $module_name)."\" alt=\"cat2\" />";
            echo " <a href=\"modules.php?name=Forums&amp;file=viewforum&amp;f=$fid\">$forum_name</a></td></tr>";
            if($xml) {
                //XML-Output
                @fwrite($var, "  <url><loc>".EVO_SERVER_URL."/modules.php?name=Forums&amp;file=viewforum&amp;f=$fid</loc><changefreq>daily</changefreq></url>\n");
            }
            $resultT = $db->sql_query("SELECT topic_title, topic_id FROM ".TOPICS_TABLE." WHERE forum_id=$fid ORDER BY topic_id DESC LIMIT 0,".$ntopics);
            while($rowT = $db->sql_fetchrow($resultT)) {
              echo"<tr><td>&nbsp;</td><td>";
              echo"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src=\"".evo_image('catt.gif', $module_name)."\" alt=\"cat\" />";
              echo" <a href=\"modules.php?name=Forums&amp;file=viewtopic&amp;t=$rowT[topic_id]\">" . $rowT['topic_title'] . "</a></td></tr>";
              if($xml) {
                  //XML-Output
                  @fwrite($var, "  <url><loc>".EVO_SERVER_URL."/modules.php?name=Forums&amp;file=viewtopic&amp;t=$rowT[topic_id]</loc></url>\n");
              }
            }
            $db->sql_freeresult($resultT);
          }
        }
        $db->sql_freeresult($result6);
      }
      $db->sql_freeresult($result5);
    break;

    case 'Sections':
      $result7 = $db->sql_query("SELECT `secid`, `secname`, `image` FROM `"._SECTIONS_TABLE."` ORDER BY `secname`");
      while ($row7 = $db->sql_fetchrow($result7)) {
        $secid = $row7['secid'];
        $secname = $row7['secname'];
        $view = $row7['view'];
        echo "<tr><td>&nbsp;</td><td>";
        if ($view == 1) {
          echo "&nbsp;&nbsp;&nbsp;&nbsp;<img src=\"".evo_image('deny.gif', $module_name)."\" alt=\"deny\" />";
        } else {
          echo "&nbsp;&nbsp;&nbsp;&nbsp;<img src=\"".evo_image('cat2.gif', $module_name)."\" alt=\"cat2\" />";
        }
        echo "<a href=\"modules.php?name=Sections&amp;op=listarticles&amp;secid=$secid\">$secname</a></td></tr>";
        if($xml) {
          //XML-Output
          @fwrite($var, "  <url><loc>".EVO_SERVER_URL."/modules.php?name=Sections&amp;op=listarticles&amp;secid=$secid</loc></url>\n");
         }
      }
      $db->sql_freeresult($result7);
    break;

    case 'Web_Links':
      $result8 = $db->sql_query("SELECT `cid`, `title` FROM `"._WEBLINKS_CATEGORIES_TABLE."` ORDER BY `title`");
      while ($row8 = $db->sql_fetchrow($result8)) {
        $linktitle = $row8['title'];
        $cid1 = $row8['cid'];
        echo "<tr><td>&nbsp;</td><td><img src=\"".evo_image('cat2.gif', $module_name)."\" alt=\"cat2\" /><a href=\"modules.php?name=Web_Links&amp;l_op=viewlink&amp;cid=$cid1\">$linktitle</a></td></tr>";
        if($xml) {
           //XML-Output
           @fwrite($var, "  <url><loc>".EVO_SERVER_URL."/modules.php?name=Web_Links&amp;l_op=viewlink&amp;cid=$cid1</loc></url>\n");
        }
      }
      $db->sql_freeresult($result8);
    break;

    case 'Topics':
      $result9 = $db->sql_query("SELECT topictext,topicid FROM "._TOPICS_TABLE." ORDER BY topictext");
      while ($row9 = $db->sql_fetchrow($result9)) {
        $topiclink = $row9['topictext'];
        $cidtopic = $row9['topicid'];
        echo "<tr><td>&nbsp;</td><td>&nbsp;&nbsp;&nbsp;&nbsp;<img src=\"".evo_image('cat2.gif', $module_name)."\" alt=\"cat2\" />&nbsp;<a href=\"modules.php?name=Topics&amp;cid=$cidtopic\">$topiclink</a></td></tr>";
        if($xml) {
           //XML-Output
           @fwrite($var, "  <url><loc>".EVO_SERVER_URL."/modules.php?name=Topics&amp;cid=$cidtopic</loc></url>\n");
        }
      }
      $db->sql_freeresult($result9);
    break;

    case 'News':
      $result10 = $db->sql_query("SELECT `title`, `sid` FROM `"._STORIES_TABLE."` ORDER BY `sid` DESC LIMIT 0,".$nnews);
      while ($row10 = $db->sql_fetchrow($result10)) {
        $newslink = $row10['title'];
        $cidnews = $row10['sid'];

        echo "<tr><td>&nbsp;</td><td>&nbsp;&nbsp;&nbsp;&nbsp;<img src=\"".evo_image('cat2.gif', $module_name)."\" alt=\"cat2\" />&nbsp;<a href=\"modules.php?name=News&amp;op=read_article&amp;sid=$cidnews\">$newslink</a></td></tr>";
        if($xml) {
          //XML-Output
          @fwrite($var, "  <url><loc>".EVO_SERVER_URL."/modules.php?name=News&amp;op=read_article&amp;sid=$cidnews</loc></url>\n");
        }
      }
      $db->sql_freeresult($result10);
    break;

    case 'Members_List':
      $result11 = $db->sql_query("SELECT `username`, `user_id` FROM `"._USERS_TABLE."` WHERE user_active = 1 ORDER BY `user_id` DESC LIMIT 0,".$nuser);
      if ($show) {
          while ($row11 = $db->sql_fetchrow($result11)) {
            $user=UsernameColor($row11['username']);
            $ciduser=$row11['user_id'];

            echo "<tr><td>&nbsp;</td><td>&nbsp;&nbsp;&nbsp;&nbsp;<img src=\"".evo_image('cat2.gif', $module_name)."\" alt=\"cat2\" />&nbsp;<a href=\"modules.php?name=Profile&amp;mode=viewprofile&amp;u=$ciduser\">$user</a></td></tr>";
          }
          $db->sql_freeresult($result11);
      }
    break;

    case 'Reviews':
      $result12 = $db->sql_query("SELECT `title`, `rid` FROM `"._REVIEWS_REVIEWS_TABLE."` ORDER BY `rid` DESC LIMIT 0,".$nrev);
      while ($row12 = $db->sql_fetchrow($result12)) {
        $titrev=$row12['title'];
        $cidrev=$row12['rid'];

        echo "<tr><td>&nbsp;</td><td>&nbsp;&nbsp;&nbsp;&nbsp;<img src=\"".evo_image('cat2.gif', $module_name)."\" alt=\"cat2\" />&nbsp;<a href=\"modules.php?name=Reviews&amp;rop=showcontent&amp;id=$cidrev\">$titrev</a></td></tr>";
        if($xml) {
          //XML-Output
          @fwrite($var, "  <url><loc>".EVO_SERVER_URL."/modules.php?name=Reviews&amp;rop=showcontent&amp;id=$cidrev</loc></url>\n");
        }
      }
      $db->sql_freeresult($result12);
    break;

  }
}
$db->sql_freeresult($result2);
echo "</table>";
CloseTable();

// YOU ARE NOT AUTHORISED TO REMOVE OR EDIT BELOW LINES WITHOUT AUTHORS PERMISSIONS. PLEASE PLAY FAIR.
// NON MOFIFICARE O RIMUOBERE LE LINEE SEGUENTI SENZA IL PERMESSO DELL'AUTORE

if($xml) {
    // FOOTER XML
    @fwrite($var, '</urlset>');
    @fclose($var);
}
// FOOTER GRAPHIC
include_once(NUKE_BASE_DIR.'footer.php');

?>